/* Categories — grilles produits relevees sur fr.jellypin.com
   Chaque ligne : slug|nom|prix|badge|suffixe d'image */
window.IMG_PREFIX = 'https://cdn11.bigcommerce.com/s-dt3q8edcif/images/stencil/500x500/products/';

window.CATEGORIES = {
  'mystere': {
    title: 'JELLYPIN MYSTÈRE', crumbs: ['Accueil', 'Collections'], count: '4',
    intro: 'Vous ne choisissez pas votre Jellypin : on le tire au sort pour vous. Du ticket à 2€ au coffret collector, la surprise est garantie.',
    dynamic: true,
    filterBadge: 'Mystère',
    rows: []
  },

  'packs-jellypin': {
    title: 'PACKS JELLYPIN', crumbs: ['Accueil', 'Collections'], count: '3',
    intro: 'Plusieurs Jellypins réunis dans un seul pack, à prix fixe et malin.',
    rows: [
      "pack-duo-fruits|Pack Duo Amuseables Fruits|49,99€|Pack|329/15945/A6PEACH__95074.1763051157.jpg",
      "pack-trio-jardin|Pack Trio Amuseables Jardin|49,99€|Pack|1867/7899/A6PCT__55754.1.jpg",
      "pack-surprise-jellypin|Pack Surprise Jellypin|49,99€|Pack|1951/16112/A4SWEE__10188.1765311964.jpg"
    ]
  },
  'nouveautes': {
    title: 'NOUVEAUTÉS', crumbs: ['Accueil'], count: '40',
    intro: 'Les tout derniers Jellypins, fraîchement arrivés dans la famille.',
    rows: [
      "amuseables-flickerty-candle|Amuseables Flickerty Candle|19,99€|Nouveauté|2087/17943/A4CAND__03438.1.jpg",
      "growlston-gargoyle|Growlston Gargoyle|9,99€|Nouveauté|2091/17956/GAR3GYL__90784.1.jpg",
      "amuseables-vampop-drink|Amuseables Vampop Drink|9,99€|Nouveauté|2089/17957/A4HALD__36340.1.jpg",
      "amuseables-peanut-cat-outfit|Amuseables Peanut ‘Cat’|19,99€|Nouveauté|1867/7899/A6PCT__55754.1.jpg",
      "broox-bat|Broox Bat|9,99€|Nouveauté|1848/9847/BAT3B__58119.1.jpg",
      "amuseables-glazespun-doughnut|Amuseables Glazespun Doughnut|19,99€|Nouveauté|2086/17941/A2DOUH__31278.1.jpg",
      "amuseables-garlic|Amuseables Garlic|9,99€|Nouveauté|2088/17946/A4GAR__06291.1.jpg",
      "ooky-jack-o-lantern|Ooky Jack O Lantern|9,99€|Nouveauté|1841/13375/OOK3JOL__56289.1.jpg",
      "rufferty-puppy-wizard-original|Rufferty Puppy 'Wizard'|19,99€|Nouveauté|2090/17969/BAS3BCPW__50540.1.jpg",
      "ghost-bob|Ghost Bob|9,99€|Nouveauté|2092/17948/GH3B__60756.1.jpg",
      "ricky-rain-frog-pouch|Pochette Ricky Rain Frog|9,99€|Nouveauté|1958/18052/RR4P__51635.1.jpg",
      "bashful-bunny-junior|Bashful Bunny Junior|9,99€|Nouveauté|2093/18024/BASJ6BC__14437.1.jpg",
      "bartholomew-bear-hiking-outfit|Bartholomew Bear ‘Hiking’|19,99€|Nouveauté|2073/17654/BARM2OD__85134.1.png",
      "bretti-yeti|Bretti Yeti|9,99€|Nouveauté|2079/17661/YEN2YET__49432.1.png",
      "amuseables-peanut-yeti-outfit|Amuseables Peanut ‘Yeti’|19,99€|Nouveauté|2072/17806/A6PBF__30852.1.jpg",
      "rockleton|Rockleton|9,99€|Nouveauté|2076/17703/R3RMON__26988.1.png",
      "amuseables-smores|Amuseables S'mores|9,99€|Nouveauté|2069/17691/A4SMR__90722.1.png",
      "amuseables-ort-tum-acorns|Amuseables Ort & Tum Acorns|9,99€|Nouveauté|2071/17685/A6PAC__55004.1.png",
      "trixiwoo-raccoon|Trixiwoo Raccoon|9,99€|Nouveauté|2077/17788/RA3CN__98746.1.jpg",
      "bartholomew-bear-sun-outfit|Bartholomew Bear ‘Sun’|19,99€|Nouveauté|2074/17633/BARM2SUN__09601.1.png",
      "amuseables-sports-fowla-red-card|Amuseables Sports Fowla Red Card|19,99€|Nouveauté|2082/17873/AS6RC__29252.1.png",
      "fluff-rescue-dog|Fluff Rescue Dog|9,99€|Nouveauté|2075/17539/BRA3DOG__88704.1.jpg",
      "scruffles-rescue-dog|Scruffles Rescue Dog|9,99€|Nouveauté|2078/17546/RES3DOG__55039.1.jpg",
      "amuseables-sports-warni-yellow-card|Amuseables Sports Warni Yellow Card|19,99€|Nouveauté|2083/17879/AS6YC__47489.1.png"
    ]
  },

  'tous-les-jellypins': {
    title: 'TOUS LES JELLYPINS', crumbs: ['Accueil'], count: '292',
    intro: 'Toute la collection Jellypin, saisons comprises.',
    rows: [
    "amuseables-flickerty-candle|Amuseables Flickerty Candle|19,99€|Nouveauté|2087/17943/A4CAND__03438.1.jpg",
    "growlston-gargoyle|Growlston Gargoyle|9,99€|Nouveauté|2091/17956/GAR3GYL__90784.1.jpg",
    "amuseables-vampop-drink|Amuseables Vampop Drink|9,99€|Nouveauté|2089/17957/A4HALD__36340.1.jpg",
    "amuseables-peanut-cat-outfit|Amuseables Peanut ‘Cat’|19,99€|Nouveauté|1867/7899/A6PCT__55754.1.jpg",
    "broox-bat|Broox Bat|9,99€|Nouveauté|1848/9847/BAT3B__58119.1.jpg",
    "amuseables-glazespun-doughnut|Amuseables Glazespun Doughnut|19,99€|Nouveauté|2086/17941/A2DOUH__31278.1.jpg",
    "amuseables-garlic|Amuseables Garlic|9,99€|Nouveauté|2088/17946/A4GAR__06291.1.jpg",
    "ooky-jack-o-lantern|Ooky Jack O Lantern|9,99€|Nouveauté|1841/13375/OOK3JOL__56289.1.jpg",
    "rufferty-puppy-wizard-original|Rufferty Puppy 'Wizard'|19,99€|Nouveauté|2090/17969/BAS3BCPW__50540.1.jpg",
    "ghost-bob|Ghost Bob|9,99€|Nouveauté|2092/17948/GH3B__60756.1.jpg",
    "ricky-rain-frog-pouch|Pochette Ricky Rain Frog|9,99€|Nouveauté|1958/18052/RR4P__51635.1.jpg",
    "bashful-bunny-junior|Bashful Bunny Junior|9,99€|Nouveauté|2093/18024/BASJ6BC__14437.1.jpg",
    "bartholomew-bear-hiking-outfit|Bartholomew Bear ‘Hiking’|19,99€|Nouveauté|2073/17654/BARM2OD__85134.1.png",
    "bretti-yeti|Bretti Yeti|9,99€|Nouveauté|2079/17661/YEN2YET__49432.1.png",
    "amuseables-peanut-yeti-outfit|Amuseables Peanut ‘Yeti’|19,99€|Nouveauté|2072/17806/A6PBF__30852.1.jpg",
    "rockleton|Rockleton|9,99€|Nouveauté|2076/17703/R3RMON__26988.1.png",
    "amuseables-smores|Amuseables S'mores|9,99€|Nouveauté|2069/17691/A4SMR__90722.1.png",
    "amuseables-ort-tum-acorns|Amuseables Ort & Tum Acorns|9,99€|Nouveauté|2071/17685/A6PAC__55004.1.png",
    "trixiwoo-raccoon|Trixiwoo Raccoon|9,99€|Nouveauté|2077/17788/RA3CN__98746.1.jpg",
    "bartholomew-bear-sun-outfit|Bartholomew Bear ‘Sun’|19,99€|Nouveauté|2074/17633/BARM2SUN__09601.1.png",
    "amuseables-sports-fowla-red-card|Amuseables Sports Fowla Red Card|19,99€|Nouveauté|2082/17873/AS6RC__29252.1.png",
    "fluff-rescue-dog|Fluff Rescue Dog|9,99€|Nouveauté|2075/17539/BRA3DOG__88704.1.jpg",
    "scruffles-rescue-dog|Scruffles Rescue Dog|9,99€|Nouveauté|2078/17546/RES3DOG__55039.1.jpg",
    "amuseables-sports-warni-yellow-card|Amuseables Sports Warni Yellow Card|19,99€|Nouveauté|2083/17879/AS6YC__47489.1.png",
    "albee-bee|Albee Bee|9,99€|De Retour en Stock|169/11610/HAP3BEE__12251.1.jpg",
    "amuseables-pink-and-white-marshmallows|Amuseables Pink and White Marshmallows|19,99€|Best Seller|1524/7915/A6MPW__01155.1.jpg",
    "blossom-blush-bunny-cherry|Blossom Blush Bunny 'Cherry'|19,99€|De Retour en Stock|1335/9035/BPS3EC__96989.1.jpg",
    "bashful-beige-bunny-petal|Blossom Beige Bunny 'Petal'|9,99€|Best Seller|1334/9063/BPM3BM__51037.1.jpg",
    "amuseables-peanut|Amuseables Peanut|9,99€|Best Seller|124/7934/A6PE__17318.1.jpg",
    "amuseables-birthday-cake|Amuseables Birthday Cake|9,99€|Best Seller|115/17861/A2BC__96104.1.jpg",
    "bashful-beige-bunny|Bashful Beige Bunny|9,99€|Best Seller|1387/8893/BAS3B__05967.1.jpg",
    "amuseables-croissant|Amuseables Croissant|9,99€|Best Seller|1783/15634/A6C__09561.1.jpg",
    "personalised-bashful-beige-bunny-medium|Bashful Beige Bunny Personnalisé (Moyen)|19,99€|Best Seller|191/15922/PERSBAS3B__19939.1.jpg",
    "bartholomew-bear-bathrobe|Bartholomew Bear ‘Bathrobe’|9,99€|Best Seller|161/15802/BARM2BR__31906.1.png",
    "bartholomew-bear|Bartholomew Bear|9,99€|Best Seller|1388/17023/BARM3BR__53106.1.jpg",
    "bashful-beige-birthday-bunny|Bashful Beige Bunny 'Birthday'|19,99€|Best Seller|164/8635/BAS3BEBB__79773.1.jpg",
    "amuseables-horatio-pistachio|Amuseables Horatio Pistachio|19,99€|Best Seller|1528/7949/A6PST__47887.1.jpg",
    "bashful-cream-bunny|Bashful Cream Bunny|9,99€|Best Seller|1393/9012/BAS3BC__56893.1.jpg",
    "amuseables-sun|Amuseables Sun|9,99€|De Retour en Stock|1376/8315/A2SUN__49465.1.jpg",
    "sky-dragon|Sky Dragon|9,99€|De Retour en Stock|1757/16657/SKY2DD__76036.1.jpg",
    "amuseables-pain-au-chocolat|Amuseables Pain Au Chocolat|19,99€|De Retour en Stock|1525/7921/A6PACHOC__34531.1.jpg",
    "timmy-turtle|Timmy Turtle|9,99€|De Retour en Stock|1764/15157/TIM3TUR__91959.1.jpg",
    "bashful-luxe-bunny-willow|Bashful Luxe Bunny Willow|9,99€|De Retour en Stock|1804/9709/BAS3WIL__19344.1.jpg",
    "bashful-luxe-bunny-rosa|Bashful Luxe Bunny Rosa|9,99€|De Retour en Stock|1800/9590/BAS3ROS__30858.1.jpg",
    "personalised-smudge-elephant-soother|Ma Première Peluche Smudge Elephant Personnalisé|19,99€|De Retour en Stock|1042/13898/PERSSMG4SE__99716.1.jpg",
    "odell-octopus|Odell Octopus|9,99€|De Retour en Stock|1735/13322/OD2OC__27964.1.jpg",
    "amuseables-peach|Amuseables Peach|9,99€|De Retour en Stock|329/15945/A6PEACH__95074.1.jpg",
    "amuseables-pair-of-marshmallows-bag-charm|Porte-clés Amuseables Pair of Marshmallows|19,99€|De Retour en Stock|1865/8357/APM4BC__02412.1.jpg",
    "amuseables-happy-boiled-egg|Amuseables Happy Boiled Egg|19,99€|De Retour en Stock|117/8225/A6BE__69286.1.jpg",
    "amuseables-storm-cloud-bag-charm|Porte-clés Amuseables Storm Cloud|19,99€|De Retour en Stock|306/7727/A4SCLBC__99460.1.jpg",
    "amuseables-fleurette-tarte-aux-fraises|Amuseables Fleurette Tarte Aux Fraises|19,99€|De Retour en Stock|337/8021/A6TAF__79113.1.jpg",
    "bashful-luxe-bunny-nimbus|Bashful Luxe Bunny Nimbus|9,99€|De Retour en Stock|1834/8663/BAS3NIM__79056.1.jpg",
    "mummy-bob|Mummy Bob|9,99€|De Retour en Stock|952/13166/MUM3B__49571.1.jpg",
    "amuseables-egglantine-egg-on-toast|Amuseables Egglantine Egg On Toast|19,99€|De Retour en Stock|264/7390/A2EGGT__77595.1.jpg",
    "amuseables-sun-musical-pull|Peluche Musicale Amuseables Sun|19,99€|De Retour en Stock|950/13165/MP4SUN__21423.1.jpg",
    "smudge-elephant-soother|Ma Première Peluche Smudge Elephant|9,99€|De Retour en Stock|1186/14691/SMG4SE__12646.1.jpg",
    "if-i-were-an-octopus-board-book|Livre « If I Were An Octopus »|19,99€|De Retour en Stock|437/9931/BB444OC__77564.1.jpg",
    "vivacious-vegetable-aubergine|Amuseables Aubergine|19,99€|En Rupture de Stock|139/15249/VV6A__75944.1.jpg",
    "derreck-dog|Derreck Dog|9,99€|En Rupture de Stock|1607/11597/GRU3DG__35675.1.jpg",
    "bashful-unicorn-2024|Bashful Unicorn|9,99€|En Rupture de Stock|1392/9827/BAS3UC__41130.1.jpg",
    "blossom-cream-bunny-berry|Blossom Cream Bunny 'Berry'|9,99€||1325/8844/BMP3MS__14714.1.jpg",
    "peanut-penguin|Peanut Penguin|9,99€||207/13523/PNM3PN__01100.1.jpg",
    "gobfrey-whale-shark|Gobfrey Whale Shark|9,99€|Best Seller|184/15365/WHL3SH__42627.1.jpg",
    "bartholomew-bear-junior|Bartholomew Bear Junior|9,99€|Best Seller|1389/17038/BARM6BO__15542.1.jpg",
    "ricky-rain-frog|Ricky Rain Frog|9,99€||210/15866/RR3F__36111.1.jpg",
    "personalised-bashful-cream-bunny-medium|Bashful Cream Bunny Personnalisé (Moyen)|19,99€|Best Seller|192/13600/PERSBAS3BC__15295.1.jpg",
    "personalised-bashful-beige-bunny-birthday|Bashful Beige Bunny 'Birthday' Personnalisé (Moyen)|19,99€|Best Seller|1649/13605/PERSBAS3BEBB__59069.1.jpg",
    "bashful-tulip-pink-bunny|Bashful Tulip Pink Bunny|9,99€|Best Seller|1766/16338/BAS3BTP__67822.1.jpg",
    "personalised-bashful-silver-bunny-medium|Bashful Silver Bunny Personnalisé (Moyen)|19,99€|Best Seller|179/13618/PERSBAS3BS__91572.1.jpg",
    "bashful-silver-bunny|Bashful Silver Bunny|9,99€||1390/9274/BAS3BS__19500.1.jpg",
    "blossom-blush-bunny-cherry-with-personalised-cream-jumper|Blossom Blush Bunny 'Cherry' avec Pull Crème Personnalisé|19,99€|Best Seller|235/12172/JUMPCBPS3EC__57216.1.jpg",
    "personalised-bashful-blush-bunny-medium|Bashful Blush Bunny Personnalisé (Moyen)|19,99€|Best Seller|193/18005/PERSBAS3BLU__58300.1.jpg",
    "personalised-bashful-tulip-bunny-medium|Bashful Tulip Bunny Personnalisé (Moyen)|19,99€|Personnalisez-Moi|194/16998/PERSBAS3BTP__88845.1.jpg",
    "blossom-cream-bunny-berry-with-personalised-cream-jumper|Blossom Cream Bunny 'Berry' avec Pull Crème Personnalisé|19,99€|Best Seller|232/12143/JUMPCBMP3MS__19307.1.jpg",
    "cream-bunny-with-star|Cream Bunny with Star|9,99€||2023/17000/BB3STAR__81835.1.jpg",
    "bashful-beige-bunny-with-personalised-cream-jumper|Bashful Bunny avec Pull Crème Personnalisé|19,99€|Personnalisez-Moi|735/15914/JUMPCBAS3B__07630.1.jpg",
    "personalised-cream-bunny-with-star|Cream Bunny with Star Personnalisé|19,99€|Personnalisez-Moi|2029/17175/PERSBB3STAR__14546.1.jpg",
    "blushkin-blossom-bunny-bag-charm|Porte-clés Blushkin Blossom Bunny|19,99€||1983/16609/BP4ROSE__16932.1.jpg",
    "hopscone-luxe-bunny|Hopscone Luxe Bunny|9,99€|Best Seller|128/8702/BAS3KUP__31073.1.jpg",
    "bashful-blush-bunny|Bashful Blush Bunny|9,99€|Best Seller|1831/15930/BAS3BLU__30145.1.jpg",
    "cream-bunny-with-plant|Cream Bunny with Plant|9,99€||2022/16947/BB3PLA__01172.1.jpg",
    "zodihop-luxe-bunny-bag-charm|Porte-clés Zodihop Luxe Bunny|19,99€||2021/17801/BAS4COSBC__59382.1.jpg",
    "amuseables-sun-roller-skates|Amuseables Sun 'Roller Skates'|19,99€||2041/17283/A2SUNRS__69040.1.jpg",
    "amuseables-lightbulb|Amuseables Lightbulb|9,99€||2025/16886/A4BULB__52534.1.jpg",
    "amuseables-zapperty-lightning-bolt|Amuseables Zapperty Lightning Bolt|19,99€|Nouveauté|2068/17697/A2BLT__02056.1.png",
    "amuseables-black-hole-bag-charm|Porte-clés Amuseables Black Hole|19,99€|Nouveauté|2012/17076/A4BHBC__06656.1.jpg",
    "amuseables-sports-walston-whistle|Amuseables Sports Walston Whistle|19,99€|Nouveauté|2081/17715/AMS4W__92020.1.png",
    "amuseables-jellypin-football|Amuseables Jellypin Football|19,99€|Nouveauté|2051/17354/AS2FB__65359.1.jpg",
    "amuseables-aubergine-bum-bag|Sac banane Amuseables Aubergine|19,99€|Nouveauté|1970/16535/A4AUBBAG__60574.1.jpg",
    "amuseables-pickle|Amuseables Pickle|9,99€|Best Seller|331/7933/A6PIC__22611.1.jpg",
    "amuseables-codhi-californian-roll|Amuseables Codhi Californian Roll|19,99€|Best Seller|2058/17457/A4CAL__49543.1.jpg",
    "amuseables-espresso-cup|Amuseables Espresso Cup|9,99€|Best Seller|1866/7812/A6EC__84335.1.jpg",
    "amuseables-margaux-madeleine|Amuseables Margaux Madeleine|19,99€|Best Seller|1974/16552/A6MAD__84222.1.jpg",
    "amuseables-bouquet-of-flowers|Amuseables Bouquet of Flowers|19,99€|Best Seller|118/7326/A2BFL__46796.1.jpg",
    "amuseables-moon|Amuseables Moon|9,99€|Best Seller|1829/8177/A2MOON__29309.1.jpg",
    "bartholomew-bear-shoulder-bag|Sac bandoulière Bartholomew Bear|19,99€|Bandoulière Ajustable|2065/17471/BAR4BGBR__38558.1.jpg",
    "amuseables-sun-shoulder-bag|Sac bandoulière Amuseables Sun|19,99€|Nouveauté|2084/17741/A4SNBG__54034.1.jpg",
    "amuseables-cirrus-storm-cloud-shoulder-bag|Sac bandoulière Amuseables Cirrus Storm Cloud|19,99€|Bandoulière Ajustable|2064/17503/A4SCLBG__70523.1.jpg",
    "amuseables-stratto-cloud-shoulder-bag|Sac bandoulière Amuseables Stratto Cloud|19,99€|Bandoulière Ajustable|2062/18171/A4CLBAG__52289.1.jpg",
    "amuseables-cherries-bag-charm|Porte-clés Amuseables Cherries|19,99€||284/15888/A4CHSBC__41385.1.jpg",
    "amuseables-shamrock-bag-charm|Porte-clés Amuseables Siofra Shamrock|19,99€|Best Seller|1947/17453/A4SHMBC__80767.1.jpg",
    "amuseables-hosomaki-key-chain-bag-charm|Porte-clés Amuseables ​Hosomaki|19,99€||2059/17609/A4CUCHBC__43537.1.jpg",
    "amuseables-peach-bag-charm|Porte-clés Amuseables Peach|19,99€|Best Seller|1969/16743/APEACH4BC__04075.1.jpg",
    "amuseables-sun-pouch|Pochette Amuseables Sun|9,99€||1511/7729/A4SUNPP__78365.1.jpg",
    "amuseables-peach-shoulder-bag|Sac Amuseables Peach|19,99€||1971/16742/A4PEACHB__17534.1.jpg",
    "peanut-penguin-pouch|Pochette Peanut Penguin|9,99€||1659/14011/PNP4PP__35417.1.jpg",
    "bartholomew-bear-pouch|Pochette Bartholomew Bear|9,99€||1558/8576/BAR4PP__67269.1.jpg",
    "little-lamb-bag|Sac Little Lamb|9,99€||914/12898/L4LB__79474.1.jpg",
    "bashful-bunny-beige-backpack|Sac à dos Bashful Beige Bunny|19,99€||411/8762/BAS4BBP__55520.1.jpg",
    "pack-duo-fruits|Pack Duo Amuseables Fruits|49,99€|Pack|329/15945/A6PEACH__95074.1763051157.jpg",
    "pack-trio-jardin|Pack Trio Amuseables Jardin|49,99€|Pack|1867/7899/A6PCT__55754.1.jpg",
    "pack-surprise-jellypin|Pack Surprise Jellypin|49,99€|Pack|1951/16112/A4SWEE__10188.1765311964.jpg",
    "maffles-manatee|Maffles Manatee|9,99€|Best Seller|2047/17306/MAN2TEE__43348.1.jpg",
    "bartholomew-bear-seafarer-outfit|Bartholomew Bear ‘Seafarer’|19,99€|Best Seller|2042/17296/BARM2FM__36365.1.jpg",
    "larry-lobster-sailor-outfit|Larry Lobster ‘Sailor’|19,99€|Best Seller|2046/17309/LOB2LAR__01918.1.jpg",
    "pingouin-bonnet-rouge|Pingouin Bonnet Rouge|19,99€|Noël|img/noel/pingouin-bonnet-rouge.jpg",
    "bonhomme-pain-d-epices|Bonhomme Pain d'Épices|19,99€|Noël|img/noel/bonhomme-pain-d-epices.jpg",
    "sapin-de-noel|Sapin de Noël|19,99€|Noël|img/noel/sapin-de-noel.jpg",
    "bonhomme-de-neige-haut-de-forme|Bonhomme de Neige Haut-de-Forme|19,99€|Noël|img/noel/bonhomme-de-neige-haut-de-forme.jpg",
    "ours-polaire-echarpe-rouge|Ours Polaire Écharpe Rouge|19,99€|Noël|img/noel/ours-polaire-echarpe-rouge.jpg",
    "mug-chocolat-chaud|Mug Chocolat Chaud|19,99€|Noël|img/noel/mug-chocolat-chaud.jpg",
    "chaussette-de-noel|Chaussette de Noël|9,99€|Noël|img/noel/chaussette-de-noel.jpg",
    "renne-pull-flocon|Renne Pull Flocon|19,99€|Noël|img/noel/renne-pull-flocon.jpg",
    "maison-en-pain-d-epices|Maison en Pain d'Épices|19,99€|Noël|img/noel/maison-en-pain-d-epices.jpg",
    "pere-noel|Père Noël|19,99€|Noël|img/noel/pere-noel.jpg",
    "cadeau-rouge-noeud-dore|Cadeau Rouge Nœud Doré|9,99€|Noël|img/noel/cadeau-rouge-noeud-dore.jpg",
    "lutin-de-noel|Lutin de Noël|19,99€|Noël|img/noel/lutin-de-noel.jpg",
    "pudding-de-noel|Pudding de Noël|9,99€|Noël|img/noel/pudding-de-noel.jpg",
    "flocon-de-neige|Flocon de Neige|9,99€|Noël|img/noel/flocon-de-neige.jpg",
    "renard-pull-rouge|Renard Pull Rouge|19,99€|Noël|img/noel/renard-pull-rouge.jpg",
    "lapin-brun|Lapin Brun|19,99€|Noël|img/noel/lapin-brun.jpg",
    "ange-de-noel|Ange de Noël|19,99€|Noël|img/noel/ange-de-noel.jpg",
    "etoile-pain-d-epices|Étoile Pain d'Épices|9,99€|Noël|img/noel/etoile-pain-d-epices.jpg",
    "pingouin-pere-noel|Pingouin Père Noël|9,99€|Noël|img/noel/pingouin-pere-noel.jpg",
    "husky-bonnet-rouge|Husky Bonnet Rouge|9,99€|Noël|img/noel/husky-bonnet-rouge.jpg",
    "renne-bonnet-vert|Renne Bonnet Vert|9,99€|Noël|img/noel/renne-bonnet-vert.jpg",
    "couronne-de-noel|Couronne de Noël|19,99€|Noël|img/noel/couronne-de-noel.jpg",
    "sucre-d-orge|Sucre d'Orge|9,99€|Noël|img/noel/sucre-d-orge.jpg",
    "mug-latte-echarpe-verte|Mug Latte Écharpe Verte|9,99€|Noël|img/noel/mug-latte-echarpe-verte.jpg",
    "pingouin-bonnet-pompon|Pingouin Bonnet Pompon|9,99€|Noël|img/noel/pingouin-bonnet-pompon.jpg",
    "renne-endormi|Renne Endormi|9,99€|Noël|img/noel/renne-endormi.jpg",
    "gnome-de-noel|Gnome de Noël|9,99€|Noël|img/noel/gnome-de-noel.jpg",
    "ours-polaire-bonnet-bleu|Ours Polaire Bonnet Bleu|19,99€|Noël|img/noel/ours-polaire-bonnet-bleu.jpg",
    "pingouin-bonnet-rouge-tricot|Pingouin Bonnet Rouge Tricot|19,99€|Noël|img/noel/pingouin-bonnet-rouge-tricot.jpg",
    "bonhomme-de-neige-echarpe-carreaux|Bonhomme de Neige Écharpe Carreaux|19,99€|Noël|img/noel/bonhomme-de-neige-echarpe-carreaux.jpg",
    "renne-echarpe-verte|Renne Écharpe Verte|19,99€|Noël|img/noel/renne-echarpe-verte.jpg",
    "lapin-echarpe-bleue|Lapin Écharpe Bleue|19,99€|Noël|img/noel/lapin-echarpe-bleue.jpg",
    "ours-blanc-pull-rouge|Ours Blanc Pull Rouge|19,99€|Noël|img/noel/ours-blanc-pull-rouge.jpg",
    "pingouin-capuche-grise|Pingouin Capuche Grise|19,99€|Noël|img/noel/pingouin-capuche-grise.jpg",
    "ours-pull-flocons|Ours Pull Flocons|19,99€|Noël|img/noel/ours-pull-flocons.jpg",
    "sapin-etoile-doree|Sapin Étoile Dorée|19,99€|Noël|img/noel/sapin-etoile-doree.jpg",
    "chouette-bonnet-bleu|Chouette Bonnet Bleu|19,99€|Noël|img/noel/chouette-bonnet-bleu.jpg",
    "renard-echarpe-verte|Renard Écharpe Verte|19,99€|Noël|img/noel/renard-echarpe-verte.jpg",
    "bonhomme-pain-d-epices-noeud|Bonhomme Pain d'Épices Nœud|19,99€|Noël|img/noel/bonhomme-pain-d-epices-noeud.jpg",
    "phoque-echarpe-bleue|Phoque Écharpe Bleue|9,99€|Noël|img/noel/phoque-echarpe-bleue.jpg",
    "renne-echarpe-rouge|Renne Écharpe Rouge|19,99€|Noël|img/noel/renne-echarpe-rouge.jpg",
    "husky-echarpe-rouge|Husky Écharpe Rouge|19,99€|Noël|img/noel/husky-echarpe-rouge.jpg",
    "mug-rouge-flocons|Mug Rouge Flocons|19,99€|Noël|img/noel/mug-rouge-flocons.jpg",
    "pingouin-bonnet-pere-noel|Pingouin Bonnet Père Noël|19,99€|Noël|img/noel/pingouin-bonnet-pere-noel.jpg",
    "chalet-pain-d-epices|Chalet Pain d'Épices|19,99€|Noël|img/noel/chalet-pain-d-epices.jpg",
    "ours-creme-bonnet-bleu|Ours Crème Bonnet Bleu|19,99€|Noël|img/noel/ours-creme-bonnet-bleu.jpg",
    "duo-pingouins-echarpes|Duo Pingouins Écharpes|19,99€|Noël|img/noel/duo-pingouins-echarpes.jpg",
    "faon-echarpe-rouge|Faon Écharpe Rouge|19,99€|Noël|img/noel/faon-echarpe-rouge.jpg",
    "bonhomme-de-neige-bonnet-raye|Bonhomme de Neige Bonnet Rayé|19,99€|Noël|img/noel/bonhomme-de-neige-bonnet-raye.jpg",
    "elephant-echarpe-rouge|Éléphant Écharpe Rouge|19,99€|Noël|img/noel/elephant-echarpe-rouge.jpg",
    "boule-blanche-houx|Boule Blanche Houx|19,99€|Noël|img/noel/boule-blanche-houx.jpg",
    "lapin-brun-echarpe-rouge|Lapin Brun Écharpe Rouge|19,99€|Noël|img/noel/lapin-brun-echarpe-rouge.jpg",
    "voiture-rouge-sapin|Voiture Rouge Sapin|19,99€|Noël|img/noel/voiture-rouge-sapin.jpg",
    "chien-cache-oreilles|Chien Cache-Oreilles|19,99€|Noël|img/noel/chien-cache-oreilles.jpg",
    "ours-bonnet-vert|Ours Bonnet Vert|19,99€|Noël|img/noel/ours-bonnet-vert.jpg",
    "cheminee-de-noel|Cheminée de Noël|9,99€|Noël|img/noel/cheminee-de-noel.jpg",
    "pingouin-cache-oreilles|Pingouin Cache-Oreilles|9,99€|Noël|img/noel/pingouin-cache-oreilles.jpg",
    "chaussette-sucre-d-orge|Chaussette Sucre d'Orge|9,99€|Noël|img/noel/chaussette-sucre-d-orge.jpg",
    "ours-polaire-bonnet-pere-noel|Ours Polaire Bonnet Père Noël|9,99€|Noël|img/noel/ours-polaire-bonnet-pere-noel.jpg",
    "paresseux-flocon|Paresseux Flocon|9,99€|Noël|img/noel/paresseux-flocon.jpg",
    "renne-blanc-echarpe|Renne Blanc Écharpe|9,99€|Noël|img/noel/renne-blanc-echarpe.jpg",
    "montagne-enneigee|Montagne Enneigée|9,99€|Noël|img/noel/montagne-enneigee.jpg",
    "sapin-pain-d-epices|Sapin Pain d'Épices|9,99€|Noël|img/noel/sapin-pain-d-epices.jpg",
    "herisson-bonnet-bleu|Hérisson Bonnet Bleu|9,99€|Noël|img/noel/herisson-bonnet-bleu.jpg",
    "mug-chantilly-cannelle|Mug Chantilly Cannelle|9,99€|Noël|img/noel/mug-chantilly-cannelle.jpg",
    "renne-bonnet-rouge|Renne Bonnet Rouge|9,99€|Noël|img/noel/renne-bonnet-rouge.jpg",
    "ours-creme-bonnet-rouge|Ours Crème Bonnet Rouge|9,99€|Noël|img/noel/ours-creme-bonnet-rouge.jpg",
    "pingouin-capuche-rouge|Pingouin Capuche Rouge|9,99€|Noël|img/noel/pingouin-capuche-rouge.jpg",
    "moufle-rouge-flocon|Moufle Rouge Flocon|9,99€|Noël|img/noel/moufle-rouge-flocon.jpg",
    "renne-echarpe-verte-mini|Renne Écharpe Verte Mini|9,99€|Noël|img/noel/renne-echarpe-verte-mini.jpg",
    "lapin-creme-echarpe-rouge|Lapin Crème Écharpe Rouge|9,99€|Noël|img/noel/lapin-creme-echarpe-rouge.jpg",
    "traineau-de-cadeaux|Traîneau de Cadeaux|9,99€|Noël|img/noel/traineau-de-cadeaux.jpg",
    "ours-blanc-echarpe-bleue|Ours Blanc Écharpe Bleue|9,99€|Noël|img/noel/ours-blanc-echarpe-bleue.jpg",
    "ours-pull-bleu|Ours Pull Bleu|9,99€|Noël|img/noel/ours-pull-bleu.jpg",
    "ours-et-son-petit|Ours et Son Petit|9,99€|Noël|img/noel/ours-et-son-petit.jpg",
    "couronne-souriante|Couronne Souriante|9,99€|Noël|img/noel/couronne-souriante.jpg",
    "pingouin-bonnet-et-echarpe|Pingouin Bonnet et Écharpe|9,99€|Noël|img/noel/pingouin-bonnet-et-echarpe.jpg",
    "ours-bonnet-renne|Ours Bonnet Renne|9,99€|Noël|img/noel/ours-bonnet-renne.jpg",
    "ours-allonge-bonnet-bleu|Ours Allongé Bonnet Bleu|9,99€|Noël|img/noel/ours-allonge-bonnet-bleu.jpg",
    "ours-polaire-echarpe-bleue|Ours Polaire Écharpe Bleue|19,99€|Hiver|img/hiver/ours-polaire-echarpe-bleue.jpg",
    "bonhomme-de-neige-bonnet-bleu|Bonhomme de Neige Bonnet Bleu|19,99€|Hiver|img/hiver/bonhomme-de-neige-bonnet-bleu.jpg",
    "renne-echarpe-flocons|Renne Écharpe Flocons|19,99€|Hiver|img/hiver/renne-echarpe-flocons.jpg",
    "loup-echarpe-bleue|Loup Écharpe Bleue|19,99€|Hiver|img/hiver/loup-echarpe-bleue.jpg",
    "mug-chocolat-cannelle|Mug Chocolat Cannelle|19,99€|Hiver|img/hiver/mug-chocolat-cannelle.jpg",
    "pingouins-en-luge|Pingouins en Luge|19,99€|Hiver|img/hiver/pingouins-en-luge.jpg",
    "bonhomme-pain-d-epices-echarpe|Bonhomme Pain d'Épices Écharpe|9,99€|Hiver|img/hiver/bonhomme-pain-d-epices-echarpe.jpg",
    "lapin-bonnet-bleu|Lapin Bonnet Bleu|19,99€|Hiver|img/hiver/lapin-bonnet-bleu.jpg",
    "morse-bonnet-rouge|Morse Bonnet Rouge|19,99€|Hiver|img/hiver/morse-bonnet-rouge.jpg",
    "flocon-de-neige-souriant|Flocon de Neige Souriant|19,99€|Hiver|img/hiver/flocon-de-neige-souriant.jpg",
    "renne-grelot|Renne Grelot|19,99€|Hiver|img/hiver/renne-grelot.jpg",
    "renard-blanc-echarpe|Renard Blanc Écharpe|19,99€|Hiver|img/hiver/renard-blanc-echarpe.jpg",
    "chalet-de-montagne|Chalet de Montagne|9,99€|Hiver|img/hiver/chalet-de-montagne.jpg",
    "bebe-phoque-echarpe|Bébé Phoque Écharpe|9,99€|Hiver|img/hiver/bebe-phoque-echarpe.jpg",
    "moufles-flocons|Moufles Flocons|9,99€|Hiver|img/hiver/moufles-flocons.jpg",
    "ours-polaire-allonge|Ours Polaire Allongé|9,99€|Hiver|img/hiver/ours-polaire-allonge.jpg",
    "pingouin-boule-de-neige|Pingouin Boule de Neige|9,99€|Hiver|img/hiver/pingouin-boule-de-neige.jpg",
    "renne-endormi-echarpe|Renne Endormi Écharpe|9,99€|Hiver|img/hiver/renne-endormi-echarpe.jpg",
    "renard-echarpe-carreaux|Renard Écharpe Carreaux|19,99€|Automne|img/automne/renard-echarpe-carreaux.jpg",
    "ours-feuille-d-erable|Ours Feuille d'Érable|19,99€|Automne|img/automne/ours-feuille-d-erable.jpg",
    "lapin-bonnet-citrouille|Lapin Bonnet Citrouille|19,99€|Automne|img/automne/lapin-bonnet-citrouille.jpg",
    "herisson-feuille-rouge|Hérisson Feuille Rouge|19,99€|Automne|img/automne/herisson-feuille-rouge.jpg",
    "ecureuil-gland|Écureuil Gland|19,99€|Automne|img/automne/ecureuil-gland.jpg",
    "oie-echarpe-rouge|Oie Écharpe Rouge|19,99€|Automne|img/automne/oie-echarpe-rouge.jpg",
    "hibou-echarpe-carreaux|Hibou Écharpe Carreaux|9,99€|Automne|img/automne/hibou-echarpe-carreaux.jpg",
    "ours-feuille-de-chene|Ours Feuille de Chêne|19,99€|Automne|img/automne/ours-feuille-de-chene.jpg",
    "citrouille-souriante|Citrouille Souriante|19,99€|Automne|img/automne/citrouille-souriante.jpg",
    "ecureuil-echarpe-automne|Écureuil Écharpe Automne|19,99€|Automne|img/automne/ecureuil-echarpe-automne.jpg",
    "champignon-rouge|Champignon Rouge|19,99€|Automne|img/automne/champignon-rouge.jpg",
    "chat-noir-citrouille|Chat Noir Citrouille|19,99€|Automne|img/automne/chat-noir-citrouille.jpg",
    "ours-couronne-de-feuilles|Ours Couronne de Feuilles|19,99€|Automne|img/automne/ours-couronne-de-feuilles.jpg",
    "raton-laveur-feuille|Raton Laveur Feuille|19,99€|Automne|img/automne/raton-laveur-feuille.jpg",
    "herisson-bonnet-rouge|Hérisson Bonnet Rouge|19,99€|Automne|img/automne/herisson-bonnet-rouge.jpg",
    "lapin-panier-d-automne|Lapin Panier d'Automne|19,99€|Automne|img/automne/lapin-panier-d-automne.jpg",
    "souche-d-arbre|Souche d'Arbre|19,99€|Automne|img/automne/souche-d-arbre.jpg",
    "panier-de-feuilles|Panier de Feuilles|9,99€|Automne|img/automne/panier-de-feuilles.jpg",
    "fantome-citrouille|Fantôme Citrouille|19,99€|Automne|img/automne/fantome-citrouille.jpg",
    "lapin-allonge-echarpe|Lapin Allongé Écharpe|19,99€|Automne|img/automne/lapin-allonge-echarpe.jpg",
    "renard-echarpe-verte-2|Renard Écharpe Verte|9,99€|Automne|img/automne/renard-echarpe-verte-2.jpg",
    "feuille-jaune|Feuille Jaune|9,99€|Automne|img/automne/feuille-jaune.jpg",
    "grosse-citrouille|Grosse Citrouille|9,99€|Automne|img/automne/grosse-citrouille.jpg",
    "elan-echarpe-carreaux|Élan Écharpe Carreaux|19,99€|Automne|img/automne/elan-echarpe-carreaux.jpg",
    "oie-bonnet-rouge|Oie Bonnet Rouge|9,99€|Automne|img/automne/oie-bonnet-rouge.jpg",
    "herisson-pomme|Hérisson Pomme|9,99€|Automne|img/automne/herisson-pomme.jpg",
    "mug-chantilly-feuille|Mug Chantilly Feuille|9,99€|Automne|img/automne/mug-chantilly-feuille.jpg",
    "ecureuil-roux-gland|Écureuil Roux Gland|9,99€|Automne|img/automne/ecureuil-roux-gland.jpg",
    "ours-chapeau-citrouille|Ours Chapeau Citrouille|9,99€|Automne|img/automne/ours-chapeau-citrouille.jpg",
    "champignon-blanc-a-pois|Champignon Blanc à Pois|9,99€|Automne|img/automne/champignon-blanc-a-pois.jpg",
    "chat-noir-feuilles|Chat Noir Feuilles|19,99€|Automne|img/automne/chat-noir-feuilles.jpg",
    "chien-echarpe-automne|Chien Écharpe Automne|9,99€|Automne|img/automne/chien-echarpe-automne.jpg",
    "renard-endormi|Renard Endormi|9,99€|Automne|img/automne/renard-endormi.jpg",
    "pile-de-livres-d-automne|Pile de Livres d'Automne|9,99€|Automne|img/automne/pile-de-livres-d-automne.jpg",
    "citrouille-latte|Citrouille Latte|9,99€|Automne|img/automne/citrouille-latte.jpg",
    "epouvantail|Épouvantail|9,99€|Automne|img/automne/epouvantail.jpg",
    "lapin-tournesols|Lapin Tournesols|9,99€|Automne|img/automne/lapin-tournesols.jpg",
    "ecureuil-rouge|Écureuil Rouge|9,99€|Automne|img/automne/ecureuil-rouge.jpg",
    "herisson-bonnet-tricot|Hérisson Bonnet Tricot|9,99€|Automne|img/automne/herisson-bonnet-tricot.jpg",
    "citrouille-feuille|Citrouille Feuille|9,99€|Automne|img/automne/citrouille-feuille.jpg",
    "lapin-bouquet-de-marguerites|Lapin Bouquet de Marguerites|19,99€|Printemps|img/printemps/lapin-bouquet-de-marguerites.jpg",
    "poussin-couronne-de-fleurs|Poussin Couronne de Fleurs|9,99€|Printemps|img/printemps/poussin-couronne-de-fleurs.jpg",
    "agneau-couronne-de-fleurs|Agneau Couronne de Fleurs|19,99€|Printemps|img/printemps/agneau-couronne-de-fleurs.jpg",
    "tulipe-rose|Tulipe Rose|9,99€|Printemps|img/printemps/tulipe-rose.jpg",
    "grenouille-marguerite|Grenouille Marguerite|9,99€|Printemps|img/printemps/grenouille-marguerite.jpg",
    "oie-rubans-fleuris|Oie Rubans Fleuris|19,99€|Printemps|img/printemps/oie-rubans-fleuris.jpg",
    "ecureuil-bouquet|Écureuil Bouquet|19,99€|Printemps|img/printemps/ecureuil-bouquet.jpg",
    "abeille|Abeille|19,99€|Printemps|img/printemps/abeille.jpg",
    "coccinelle|Coccinelle|19,99€|Printemps|img/printemps/coccinelle.jpg",
    "oiseau-bleu-couronne|Oiseau Bleu Couronne|19,99€|Printemps|img/printemps/oiseau-bleu-couronne.jpg",
    "lapin-carotte|Lapin Carotte|19,99€|Printemps|img/printemps/lapin-carotte.jpg",
    "papillon-pastel|Papillon Pastel|19,99€|Printemps|img/printemps/papillon-pastel.jpg",
    "marguerite-souriante|Marguerite Souriante|9,99€|Printemps|img/printemps/marguerite-souriante.jpg",
    "faon-couronne-de-fleurs|Faon Couronne de Fleurs|19,99€|Printemps|img/printemps/faon-couronne-de-fleurs.jpg",
    "escargot-couronne|Escargot Couronne|19,99€|Printemps|img/printemps/escargot-couronne.jpg",
    "lapin-creme-noeud-rose|Lapin Crème Nœud Rose|19,99€|Printemps|img/printemps/lapin-creme-noeud-rose.jpg",
    "arrosoir-fleuri-vert|Arrosoir Fleuri Vert|19,99€|Printemps|img/printemps/arrosoir-fleuri-vert.jpg",
    "herisson-couronne-de-fleurs|Hérisson Couronne de Fleurs|9,99€|Printemps|img/printemps/herisson-couronne-de-fleurs.jpg",
    "lapin-rose-couronne|Lapin Rose Couronne|19,99€|Printemps|img/printemps/lapin-rose-couronne.jpg",
    "pot-de-fleurs-marguerites|Pot de Fleurs Marguerites|9,99€|Printemps|img/printemps/pot-de-fleurs-marguerites.jpg",
    "caneton-noeud-bleu|Caneton Nœud Bleu|9,99€|Printemps|img/printemps/caneton-noeud-bleu.jpg",
    "agneau-noeud-lavande|Agneau Nœud Lavande|19,99€|Printemps|img/printemps/agneau-noeud-lavande.jpg",
    "abeille-ailes-deployees|Abeille Ailes Déployées|9,99€|Printemps|img/printemps/abeille-ailes-deployees.jpg",
    "fleur-rose|Fleur Rose|19,99€|Printemps|img/printemps/fleur-rose.jpg",
    "duo-de-cerises|Duo de Cerises|19,99€|Printemps|img/printemps/duo-de-cerises.jpg",
    "lapin-creme-bouquet|Lapin Crème Bouquet|9,99€|Printemps|img/printemps/lapin-creme-bouquet.jpg",
    "grenouille-verte|Grenouille Verte|9,99€|Printemps|img/printemps/grenouille-verte.jpg",
    "arrosoir-violet|Arrosoir Violet|9,99€|Printemps|img/printemps/arrosoir-violet.jpg",
    "oie-couronne-fleurie|Oie Couronne Fleurie|9,99€|Printemps|img/printemps/oie-couronne-fleurie.jpg",
    "panier-de-fleurs|Panier de Fleurs|19,99€|Printemps|img/printemps/panier-de-fleurs.jpg",
    "lapin-bandana-fleuri|Lapin Bandana Fleuri|19,99€|Printemps|img/printemps/lapin-bandana-fleuri.jpg",
    "carotte|Carotte|9,99€|Printemps|img/printemps/carotte.jpg",
    "marguerite-blanche|Marguerite Blanche|9,99€|Printemps|img/printemps/marguerite-blanche.jpg",
    "lapin-bleu-noeud|Lapin Bleu Nœud|9,99€|Printemps|img/printemps/lapin-bleu-noeud.jpg",
    "poussin-couronne-fleurie|Poussin Couronne Fleurie|9,99€|Printemps|img/printemps/poussin-couronne-fleurie.jpg",
    "faon-allonge-fleurs|Faon Allongé Fleurs|19,99€|Printemps|img/printemps/faon-allonge-fleurs.jpg",
    "bouquet-de-tulipes|Bouquet de Tulipes|9,99€|Printemps|img/printemps/bouquet-de-tulipes.jpg",
    "chenille|Chenille|9,99€|Printemps|img/printemps/chenille.jpg",
    "coccinelle-noire|Coccinelle Noire|9,99€|Printemps|img/printemps/coccinelle-noire.jpg",
    "papillon-rose|Papillon Rose|9,99€|Printemps|img/printemps/papillon-rose.jpg"
    ]
  },

  'animaux': {
    title: 'ANIMAUX', crumbs: ['Accueil'], count: '272',
    intro: 'De la jungle à l’océan, tout un règne animal prêt aux câlins.',
    subs: [
      ['Tous les Animaux', 'animaux'], ['Tous les Lapins', 'lapins'],
      ['Amphibiens & Reptiles', 'animaux'], ['Arctique & Antarctique', 'animaux'],
      ['Ours', 'animaux'], ['Oiseaux', 'animaux'], ['Chats & Chatons', 'animaux'],
      ['Chiens & Chiots', 'animaux'], ['Dragons & Dinosaures', 'animaux'],
      ['Jungle & Safari', 'animaux'], ['Créatures Fantastiques', 'animaux'],
      ['Océan', 'animaux'], ['Animaux de Compagnie', 'animaux'], ['Animaux de la Forêt', 'animaux']
    ],
    rows: [
      "albee-bee|Albee Bee|9,99€|De Retour en Stock|169/11610/HAP3BEE__12251.1.jpg",
      "trixiwoo-raccoon|Trixiwoo Raccoon|9,99€|Nouveauté|2077/17788/RA3CN__98746.1.jpg",
      "amuseables-peanut-cat-outfit|Amuseables Peanut ‘Cat’|19,99€|Nouveauté|1867/7899/A6PCT__55754.1.jpg",
      "bretti-yeti|Bretti Yeti|9,99€|Nouveauté|2079/17661/YEN2YET__49432.1.png",
      "growlston-gargoyle|Growlston Gargoyle|9,99€|Nouveauté|2091/17956/GAR3GYL__90784.1.jpg",
      "bashful-bunny-junior|Bashful Bunny Junior|9,99€|Nouveauté|2093/18024/BASJ6BC__14437.1.jpg",
      "bartholomew-bear-hiking-outfit|Bartholomew Bear ‘Hiking’|19,99€|Nouveauté|2073/17654/BARM2OD__85134.1.png",
      "ghost-bob|Ghost Bob|9,99€|Nouveauté|2092/17948/GH3B__60756.1.jpg",
      "rufferty-puppy-wizard-original|Rufferty Puppy 'Wizard'|19,99€|Nouveauté|2090/17969/BAS3BCPW__50540.1.jpg",
      "bartholomew-bear-sun-outfit|Bartholomew Bear ‘Sun’|19,99€|Nouveauté|2074/17633/BARM2SUN__09601.1.png",
      "rockleton|Rockleton|9,99€|Nouveauté|2076/17703/R3RMON__26988.1.png",
      "fluff-rescue-dog|Fluff Rescue Dog|9,99€|Nouveauté|2075/17539/BRA3DOG__88704.1.jpg",
      "scruffles-rescue-dog|Scruffles Rescue Dog|9,99€|Nouveauté|2078/17546/RES3DOG__55039.1.jpg",
      "ricky-rain-frog-pouch|Pochette Ricky Rain Frog|9,99€|Nouveauté|1958/18052/RR4P__51635.1.jpg",
      "blossom-blush-bunny-cherry|Blossom Blush Bunny 'Cherry'|19,99€|De Retour en Stock|1335/9035/BPS3EC__96989.1.jpg",
      "bashful-beige-bunny-petal|Blossom Beige Bunny 'Petal'|9,99€|Best Seller|1334/9063/BPM3BM__51037.1.jpg",
      "blossom-cream-bunny-berry|Blossom Cream Bunny 'Berry'|9,99€||1325/8844/BMP3MS__14714.1.jpg",
      "bashful-beige-bunny|Bashful Beige Bunny|9,99€|Best Seller|1387/8893/BAS3B__05967.1.jpg",
      "bartholomew-bear-bathrobe|Bartholomew Bear ‘Bathrobe’|9,99€|Best Seller|161/15802/BARM2BR__31906.1.png",
      "bartholomew-bear|Bartholomew Bear|9,99€|Best Seller|1388/17023/BARM3BR__53106.1.jpg",
      "bashful-beige-birthday-bunny|Bashful Beige Bunny 'Birthday'|19,99€|Best Seller|164/8635/BAS3BEBB__79773.1.jpg",
      "peanut-penguin|Peanut Penguin|9,99€||207/13523/PNM3PN__01100.1.jpg",
      "timmy-turtle|Timmy Turtle|9,99€|De Retour en Stock|1764/15157/TIM3TUR__91959.1.jpg",
      "sky-dragon|Sky Dragon|9,99€|De Retour en Stock|1757/16657/SKY2DD__76036.1.jpg",
      "gobfrey-whale-shark|Gobfrey Whale Shark|9,99€|Best Seller|184/15365/WHL3SH__42627.1.jpg",
      "bartholomew-bear-junior|Bartholomew Bear Junior|9,99€|Best Seller|1389/17038/BARM6BO__15542.1.jpg",
      "ricky-rain-frog|Ricky Rain Frog|9,99€||210/15866/RR3F__36111.1.jpg",
      "odell-octopus|Odell Octopus|9,99€|De Retour en Stock|1735/13322/OD2OC__27964.1.jpg"
    ]
  },

  'lapins': {
    title: 'LAPINS', crumbs: ['Accueil', 'Animaux'], count: '144',
    intro: 'Roses, bleus, fleuris ou curly : un arc-en-ciel de lapins prêts à bondir dans votre vie !',
    rows: [
      "bashful-bunny-junior|Bashful Bunny Junior|9,99€|Nouveauté|2093/18024/BASJ6BC__14437.1.jpg",
      "blossom-blush-bunny-cherry|Blossom Blush Bunny 'Cherry'|19,99€|De Retour en Stock|1335/9035/BPS3EC__96989.1.jpg",
      "bashful-beige-birthday-bunny|Bashful Beige Bunny 'Birthday'|19,99€|Best Seller|164/8635/BAS3BEBB__79773.1.jpg",
      "bashful-beige-bunny-petal|Blossom Beige Bunny 'Petal'|9,99€|Best Seller|1334/9063/BPM3BM__51037.1.jpg",
      "blossom-cream-bunny-berry|Blossom Cream Bunny 'Berry'|9,99€||1325/8844/BMP3MS__14714.1.jpg",
      "bashful-beige-bunny|Bashful Beige Bunny|9,99€|Best Seller|1387/8893/BAS3B__05967.1.jpg",
      "personalised-bashful-beige-bunny-medium|Bashful Beige Bunny Personnalisé (Moyen)|19,99€|Best Seller|191/15922/PERSBAS3B__19939.1.jpg",
      "bashful-cream-bunny|Bashful Cream Bunny|9,99€|Best Seller|1393/9012/BAS3BC__56893.1.jpg",
      "personalised-bashful-cream-bunny-medium|Bashful Cream Bunny Personnalisé (Moyen)|19,99€|Best Seller|192/13600/PERSBAS3BC__15295.1.jpg",
      "personalised-bashful-beige-bunny-birthday|Bashful Beige Bunny 'Birthday' Personnalisé (Moyen)|19,99€|Best Seller|1649/13605/PERSBAS3BEBB__59069.1.jpg",
      "bashful-tulip-pink-bunny|Bashful Tulip Pink Bunny|9,99€|Best Seller|1766/16338/BAS3BTP__67822.1.jpg",
      "personalised-bashful-silver-bunny-medium|Bashful Silver Bunny Personnalisé (Moyen)|19,99€|Best Seller|179/13618/PERSBAS3BS__91572.1.jpg",
      "bashful-silver-bunny|Bashful Silver Bunny|9,99€||1390/9274/BAS3BS__19500.1.jpg",
      "blossom-blush-bunny-cherry-with-personalised-cream-jumper|Blossom Blush Bunny 'Cherry' avec Pull Crème Personnalisé|19,99€|Best Seller|235/12172/JUMPCBPS3EC__57216.1.jpg",
      "personalised-bashful-blush-bunny-medium|Bashful Blush Bunny Personnalisé (Moyen)|19,99€|Best Seller|193/18005/PERSBAS3BLU__58300.1.jpg",
      "personalised-bashful-tulip-bunny-medium|Bashful Tulip Bunny Personnalisé (Moyen)|19,99€|Personnalisez-Moi|194/16998/PERSBAS3BTP__88845.1.jpg",
      "blossom-cream-bunny-berry-with-personalised-cream-jumper|Blossom Cream Bunny 'Berry' avec Pull Crème Personnalisé|19,99€|Best Seller|232/12143/JUMPCBMP3MS__19307.1.jpg",
      "cream-bunny-with-star|Cream Bunny with Star|9,99€||2023/17000/BB3STAR__81835.1.jpg",
      "bashful-beige-bunny-with-personalised-cream-jumper|Bashful Bunny avec Pull Crème Personnalisé|19,99€|Personnalisez-Moi|735/15914/JUMPCBAS3B__07630.1.jpg",
      "personalised-cream-bunny-with-star|Cream Bunny with Star Personnalisé|19,99€|Personnalisez-Moi|2029/17175/PERSBB3STAR__14546.1.jpg",
      "blushkin-blossom-bunny-bag-charm|Porte-clés Blushkin Blossom Bunny|19,99€||1983/16609/BP4ROSE__16932.1.jpg",
      "bashful-luxe-bunny-nimbus|Bashful Luxe Bunny Nimbus|9,99€|De Retour en Stock|1834/8663/BAS3NIM__79056.1.jpg",
      "hopscone-luxe-bunny|Hopscone Luxe Bunny|9,99€|Best Seller|128/8702/BAS3KUP__31073.1.jpg",
      "bashful-blush-bunny|Bashful Blush Bunny|9,99€|Best Seller|1831/15930/BAS3BLU__30145.1.jpg",
      "cream-bunny-with-plant|Cream Bunny with Plant|9,99€||2022/16947/BB3PLA__01172.1.jpg",
      "zodihop-luxe-bunny-bag-charm|Porte-clés Zodihop Luxe Bunny|19,99€||2021/17801/BAS4COSBC__59382.1.jpg",
      "bashful-luxe-bunny-willow|Bashful Luxe Bunny Willow|9,99€|De Retour en Stock|1804/9709/BAS3WIL__19344.1.jpg"
    ]
  },

  'amuseables': {
    title: 'AMUSEABLES', crumbs: ['Accueil'], count: '157',
    intro: 'Des objets du quotidien qui prennent vie, avec des yeux malicieux et de petites bottines.',
    subs: [
      ['Amuseables Gourmands', 'amuseables'], ['Amuseables Objets', 'amuseables'],
      ['Amuseables Botaniques', 'amuseables'], ['Amuseables Sportifs', 'amuseables']
    ],
    rows: [
      "amuseables-garlic|Amuseables Garlic|9,99€|Nouveauté|2088/17946/A4GAR__06291.1.jpg",
      "amuseables-peanut-cat-outfit|Amuseables Peanut ‘Cat’|19,99€|Nouveauté|1867/7899/A6PCT__55754.1.jpg",
      "amuseables-ort-tum-acorns|Amuseables Ort & Tum Acorns|9,99€|Nouveauté|2071/17685/A6PAC__55004.1.png",
      "amuseables-glazespun-doughnut|Amuseables Glazespun Doughnut|19,99€|Nouveauté|2086/17941/A2DOUH__31278.1.jpg",
      "amuseables-vampop-drink|Amuseables Vampop Drink|9,99€|Nouveauté|2089/17957/A4HALD__36340.1.jpg",
      "amuseables-flickerty-candle|Amuseables Flickerty Candle|19,99€|Nouveauté|2087/17943/A4CAND__03438.1.jpg",
      "amuseables-sun-roller-skates|Amuseables Sun 'Roller Skates'|19,99€||2041/17283/A2SUNRS__69040.1.jpg",
      "amuseables-horatio-pistachio|Amuseables Horatio Pistachio|19,99€|Best Seller|1528/7949/A6PST__47887.1.jpg",
      "amuseables-lightbulb|Amuseables Lightbulb|9,99€||2025/16886/A4BULB__52534.1.jpg",
      "ooky-jack-o-lantern|Ooky Jack O Lantern|9,99€|Nouveauté|1841/13375/OOK3JOL__56289.1.jpg",
      "amuseables-peanut-yeti-outfit|Amuseables Peanut ‘Yeti’|19,99€|Nouveauté|2072/17806/A6PBF__30852.1.jpg",
      "amuseables-smores|Amuseables S'mores|9,99€|Nouveauté|2069/17691/A4SMR__90722.1.png",
      "amuseables-sports-fowla-red-card|Amuseables Sports Fowla Red Card|19,99€|Nouveauté|2082/17873/AS6RC__29252.1.png",
      "amuseables-sports-warni-yellow-card|Amuseables Sports Warni Yellow Card|19,99€|Nouveauté|2083/17879/AS6YC__47489.1.png",
      "amuseables-zapperty-lightning-bolt|Amuseables Zapperty Lightning Bolt|19,99€|Nouveauté|2068/17697/A2BLT__02056.1.png",
      "amuseables-black-hole-bag-charm|Porte-clés Amuseables Black Hole|19,99€|Nouveauté|2012/17076/A4BHBC__06656.1.jpg",
      "amuseables-sports-walston-whistle|Amuseables Sports Walston Whistle|19,99€|Nouveauté|2081/17715/AMS4W__92020.1.png",
      "amuseables-jellypin-football|Amuseables Jellypin Football|19,99€|Nouveauté|2051/17354/AS2FB__65359.1.jpg",
      "amuseables-aubergine-bum-bag|Sac banane Amuseables Aubergine|19,99€|Nouveauté|1970/16535/A4AUBBAG__60574.1.jpg",
      "amuseables-peanut|Amuseables Peanut|9,99€|Best Seller|124/7934/A6PE__17318.1.jpg",
      "amuseables-birthday-cake|Amuseables Birthday Cake|9,99€|Best Seller|115/17861/A2BC__96104.1.jpg",
      "amuseables-croissant|Amuseables Croissant|9,99€|Best Seller|1783/15634/A6C__09561.1.jpg",
      "amuseables-pink-and-white-marshmallows|Amuseables Pink and White Marshmallows|19,99€|Best Seller|1524/7915/A6MPW__01155.1.jpg",
      "amuseables-pickle|Amuseables Pickle|9,99€|Best Seller|331/7933/A6PIC__22611.1.jpg",
      "amuseables-peach|Amuseables Peach|9,99€|De Retour en Stock|329/15945/A6PEACH__95074.1.jpg",
      "amuseables-codhi-californian-roll|Amuseables Codhi Californian Roll|19,99€|Best Seller|2058/17457/A4CAL__49543.1.jpg",
      "amuseables-espresso-cup|Amuseables Espresso Cup|9,99€|Best Seller|1866/7812/A6EC__84335.1.jpg",
      "amuseables-margaux-madeleine|Amuseables Margaux Madeleine|19,99€|Best Seller|1974/16552/A6MAD__84222.1.jpg",
      "amuseables-pain-au-chocolat|Amuseables Pain Au Chocolat|19,99€|De Retour en Stock|1525/7921/A6PACHOC__34531.1.jpg",
      "amuseables-bouquet-of-flowers|Amuseables Bouquet of Flowers|19,99€|Best Seller|118/7326/A2BFL__46796.1.jpg",
      "amuseables-moon|Amuseables Moon|9,99€|Best Seller|1829/8177/A2MOON__29309.1.jpg"
    ]
  },

  'accessoires': {
    title: 'ACCESSOIRES', crumbs: ['Accueil'], count: '55',
    intro: 'Sacs, pochettes et porte-clés pour emmener un Jellypin partout avec vous.',
    subs: [['Sacs & Pochettes', 'accessoires'], ['Porte-clés', 'accessoires'], ['Chapeaux & Écharpes', 'accessoires']],
    rows: [
      "ricky-rain-frog-pouch|Pochette Ricky Rain Frog|9,99€|Nouveauté|1958/18052/RR4P__51635.1.jpg",
      "bartholomew-bear-shoulder-bag|Sac bandoulière Bartholomew Bear|19,99€|Bandoulière Ajustable|2065/17471/BAR4BGBR__38558.1.jpg",
      "amuseables-black-hole-bag-charm|Porte-clés Amuseables Black Hole|19,99€|Nouveauté|2012/17076/A4BHBC__06656.1.jpg",
      "amuseables-sun-shoulder-bag|Sac bandoulière Amuseables Sun|19,99€|Nouveauté|2084/17741/A4SNBG__54034.1.jpg",
      "amuseables-cirrus-storm-cloud-shoulder-bag|Sac bandoulière Amuseables Cirrus Storm Cloud|19,99€|Bandoulière Ajustable|2064/17503/A4SCLBG__70523.1.jpg",
      "amuseables-stratto-cloud-shoulder-bag|Sac bandoulière Amuseables Stratto Cloud|19,99€|Bandoulière Ajustable|2062/18171/A4CLBAG__52289.1.jpg",
      "amuseables-aubergine-bum-bag|Sac banane Amuseables Aubergine|19,99€|Nouveauté|1970/16535/A4AUBBAG__60574.1.jpg",
      "amuseables-pair-of-marshmallows-bag-charm|Porte-clés Amuseables Pair of Marshmallows|19,99€|De Retour en Stock|1865/8357/APM4BC__02412.1.jpg",
      "amuseables-cherries-bag-charm|Porte-clés Amuseables Cherries|19,99€||284/15888/A4CHSBC__41385.1.jpg",
      "amuseables-storm-cloud-bag-charm|Porte-clés Amuseables Storm Cloud|19,99€|De Retour en Stock|306/7727/A4SCLBC__99460.1.jpg",
      "amuseables-shamrock-bag-charm|Porte-clés Amuseables Siofra Shamrock|19,99€|Best Seller|1947/17453/A4SHMBC__80767.1.jpg",
      "blushkin-blossom-bunny-bag-charm|Porte-clés Blushkin Blossom Bunny|19,99€||1983/16609/BP4ROSE__16932.1.jpg",
      "amuseables-hosomaki-key-chain-bag-charm|Porte-clés Amuseables ​Hosomaki|19,99€||2059/17609/A4CUCHBC__43537.1.jpg",
      "amuseables-peach-bag-charm|Porte-clés Amuseables Peach|19,99€|Best Seller|1969/16743/APEACH4BC__04075.1.jpg",
      "zodihop-luxe-bunny-bag-charm|Porte-clés Zodihop Luxe Bunny|19,99€||2021/17801/BAS4COSBC__59382.1.jpg",
      "amuseables-sun-pouch|Pochette Amuseables Sun|9,99€||1511/7729/A4SUNPP__78365.1.jpg",
      "amuseables-peach-shoulder-bag|Sac Amuseables Peach|19,99€||1971/16742/A4PEACHB__17534.1.jpg",
      "peanut-penguin-pouch|Pochette Peanut Penguin|9,99€||1659/14011/PNP4PP__35417.1.jpg",
      "bartholomew-bear-pouch|Pochette Bartholomew Bear|9,99€||1558/8576/BAR4PP__67269.1.jpg",
      "little-lamb-bag|Sac Little Lamb|9,99€||914/12898/L4LB__79474.1.jpg",
      "bashful-bunny-beige-backpack|Sac à dos Bashful Beige Bunny|19,99€||411/8762/BAS4BBP__55520.1.jpg"
    ]
  },

  'best-sellers': {
    title: 'BEST SELLERS', crumbs: ['Accueil', 'Collections'], count: '173',
    intro: 'Les Jellypins préférés, ceux qu’on adopte encore et encore.',
    rows: [
      "albee-bee|Albee Bee|9,99€|De Retour en Stock|169/11610/HAP3BEE__12251.1.jpg",
      "amuseables-pink-and-white-marshmallows|Amuseables Pink and White Marshmallows|19,99€|Best Seller|1524/7915/A6MPW__01155.1.jpg",
      "amuseables-smores|Amuseables S'mores|9,99€|Nouveauté|2069/17691/A4SMR__90722.1.png",
      "amuseables-ort-tum-acorns|Amuseables Ort & Tum Acorns|9,99€|Nouveauté|2071/17685/A6PAC__55004.1.png",
      "amuseables-peanut-cat-outfit|Amuseables Peanut ‘Cat’|19,99€|Nouveauté|1867/7899/A6PCT__55754.1.jpg",
      "bartholomew-bear-hiking-outfit|Bartholomew Bear ‘Hiking’|19,99€|Nouveauté|2073/17654/BARM2OD__85134.1.png",
      "trixiwoo-raccoon|Trixiwoo Raccoon|9,99€|Nouveauté|2077/17788/RA3CN__98746.1.jpg",
      "bartholomew-bear-sun-outfit|Bartholomew Bear ‘Sun’|19,99€|Nouveauté|2074/17633/BARM2SUN__09601.1.png",
      "amuseables-peanut-yeti-outfit|Amuseables Peanut ‘Yeti’|19,99€|Nouveauté|2072/17806/A6PBF__30852.1.jpg",
      "rockleton|Rockleton|9,99€|Nouveauté|2076/17703/R3RMON__26988.1.png",
      "fluff-rescue-dog|Fluff Rescue Dog|9,99€|Nouveauté|2075/17539/BRA3DOG__88704.1.jpg",
      "scruffles-rescue-dog|Scruffles Rescue Dog|9,99€|Nouveauté|2078/17546/RES3DOG__55039.1.jpg",
      "blossom-blush-bunny-cherry|Blossom Blush Bunny 'Cherry'|19,99€|De Retour en Stock|1335/9035/BPS3EC__96989.1.jpg",
      "bashful-beige-bunny-petal|Blossom Beige Bunny 'Petal'|9,99€|Best Seller|1334/9063/BPM3BM__51037.1.jpg",
      "amuseables-peanut|Amuseables Peanut|9,99€|Best Seller|124/7934/A6PE__17318.1.jpg",
      "amuseables-birthday-cake|Amuseables Birthday Cake|9,99€|Best Seller|115/17861/A2BC__96104.1.jpg",
      "bashful-beige-bunny|Bashful Beige Bunny|9,99€|Best Seller|1387/8893/BAS3B__05967.1.jpg",
      "amuseables-croissant|Amuseables Croissant|9,99€|Best Seller|1783/15634/A6C__09561.1.jpg",
      "personalised-bashful-beige-bunny-medium|Bashful Beige Bunny Personnalisé (Moyen)|19,99€|Best Seller|191/15922/PERSBAS3B__19939.1.jpg",
      "bartholomew-bear-bathrobe|Bartholomew Bear ‘Bathrobe’|9,99€|Best Seller|161/15802/BARM2BR__31906.1.png",
      "bartholomew-bear|Bartholomew Bear|9,99€|Best Seller|1388/17023/BARM3BR__53106.1.jpg",
      "bashful-beige-birthday-bunny|Bashful Beige Bunny 'Birthday'|19,99€|Best Seller|164/8635/BAS3BEBB__79773.1.jpg",
      "amuseables-horatio-pistachio|Amuseables Horatio Pistachio|19,99€|Best Seller|1528/7949/A6PST__47887.1.jpg",
      "bashful-cream-bunny|Bashful Cream Bunny|9,99€|Best Seller|1393/9012/BAS3BC__56893.1.jpg"
    ]
  },

  'de-retour-en-stock': {
    title: 'DE RETOUR EN STOCK', crumbs: ['Accueil', 'Collections'], count: '25',
    intro: 'Ils étaient partis, les voilà de retour.',
    rows: [
      "amuseables-sun|Amuseables Sun|9,99€|De Retour en Stock|1376/8315/A2SUN__49465.1.jpg",
      "sky-dragon|Sky Dragon|9,99€|De Retour en Stock|1757/16657/SKY2DD__76036.1.jpg",
      "amuseables-pain-au-chocolat|Amuseables Pain Au Chocolat|19,99€|De Retour en Stock|1525/7921/A6PACHOC__34531.1.jpg",
      "timmy-turtle|Timmy Turtle|9,99€|De Retour en Stock|1764/15157/TIM3TUR__91959.1.jpg",
      "albee-bee|Albee Bee|9,99€|De Retour en Stock|169/11610/HAP3BEE__12251.1.jpg",
      "bashful-luxe-bunny-willow|Bashful Luxe Bunny Willow|9,99€|De Retour en Stock|1804/9709/BAS3WIL__19344.1.jpg",
      "bashful-luxe-bunny-rosa|Bashful Luxe Bunny Rosa|9,99€|De Retour en Stock|1800/9590/BAS3ROS__30858.1.jpg",
      "personalised-smudge-elephant-soother|Ma Première Peluche Smudge Elephant Personnalisé|19,99€|De Retour en Stock|1042/13898/PERSSMG4SE__99716.1.jpg",
      "odell-octopus|Odell Octopus|9,99€|De Retour en Stock|1735/13322/OD2OC__27964.1.jpg",
      "blossom-blush-bunny-cherry|Blossom Blush Bunny 'Cherry'|19,99€|De Retour en Stock|1335/9035/BPS3EC__96989.1.jpg",
      "amuseables-peach|Amuseables Peach|9,99€|De Retour en Stock|329/15945/A6PEACH__95074.1.jpg",
      "amuseables-pair-of-marshmallows-bag-charm|Porte-clés Amuseables Pair of Marshmallows|19,99€|De Retour en Stock|1865/8357/APM4BC__02412.1.jpg",
      "amuseables-happy-boiled-egg|Amuseables Happy Boiled Egg|19,99€|De Retour en Stock|117/8225/A6BE__69286.1.jpg",
      "amuseables-storm-cloud-bag-charm|Porte-clés Amuseables Storm Cloud|19,99€|De Retour en Stock|306/7727/A4SCLBC__99460.1.jpg",
      "amuseables-fleurette-tarte-aux-fraises|Amuseables Fleurette Tarte Aux Fraises|19,99€|De Retour en Stock|337/8021/A6TAF__79113.1.jpg",
      "bashful-luxe-bunny-nimbus|Bashful Luxe Bunny Nimbus|9,99€|De Retour en Stock|1834/8663/BAS3NIM__79056.1.jpg",
      "mummy-bob|Mummy Bob|9,99€|De Retour en Stock|952/13166/MUM3B__49571.1.jpg",
      "amuseables-egglantine-egg-on-toast|Amuseables Egglantine Egg On Toast|19,99€|De Retour en Stock|264/7390/A2EGGT__77595.1.jpg",
      "amuseables-sun-musical-pull|Peluche Musicale Amuseables Sun|19,99€|De Retour en Stock|950/13165/MP4SUN__21423.1.jpg",
      "smudge-elephant-soother|Ma Première Peluche Smudge Elephant|9,99€|De Retour en Stock|1186/14691/SMG4SE__12646.1.jpg",
      "if-i-were-an-octopus-board-book|Livre « If I Were An Octopus »|19,99€|De Retour en Stock|437/9931/BB444OC__77564.1.jpg",
      "vivacious-vegetable-aubergine|Amuseables Aubergine|19,99€|En Rupture de Stock|139/15249/VV6A__75944.1.jpg",
      "derreck-dog|Derreck Dog|9,99€|En Rupture de Stock|1607/11597/GRU3DG__35675.1.jpg",
      "bashful-unicorn-2024|Bashful Unicorn|9,99€|En Rupture de Stock|1392/9827/BAS3UC__41130.1.jpg"
    ]
  },

  /* Pages d'atterrissage : uniquement des sous-categories, comme sur le site */
  'collections': {
    title: 'COLLECTIONS', crumbs: ['Accueil'], landing: true,
    intro: 'Explorez les collections Jellypin, saison après saison.',
    subs: [
      ['Noël', 'noel'], ['Hiver', 'hiver'], ['Automne', 'automne'], ['Printemps', 'printemps'],
      ['Automne & Hiver', 'nouveautes'], ['Printemps & Été', 'nouveautes'],
      ['Space', 'amuseables'], ['Best Sellers', 'best-sellers'], ['Bientôt Disponible', 'nouveautes'],
      ['De Retour en Stock', 'de-retour-en-stock'], ['Toutes les Peluches', 'tous-les-jellypins'],
      ['Bashful Bunnies', 'lapins'], ['Tous les Bashfuls', 'lapins'],
      ['Bartholomew Bear & ses Amis', 'animaux'], ['Petites Peluches', 'tous-les-jellypins'],
      ['Peluches Habillées', 'tous-les-jellypins'], ['Ultra Doux & Câlin', 'tous-les-jellypins']
    ]
  },

  'bebe': {
    title: 'BÉBÉ', crumbs: ['Accueil'], landing: true,
    intro: 'Des premières peluches toutes douces, pensées pour les tout-petits.',
    subs: [
      ['Cadeaux Bébé', 'tous-les-jellypins'], ['Puériculture & Jouets d’Éveil', 'tous-les-jellypins'],
      ['Cadeaux Bébé Personnalisés', 'personnalisation'], ['Couvertures & Premières Peluches', 'tous-les-jellypins']
    ]
  },

  'livres': {
    title: 'LIVRES', crumbs: ['Accueil'], landing: true,
    intro: 'Plongez dans le monde merveilleux de notre bibliothèque Jellypin et des fabuleuses histoires qui s’y cachent.',
    subs: [
      ['Livres d’Histoires', 'tous-les-jellypins'], ['Livres en Tissu', 'tous-les-jellypins'],
      ['Livres « Si j’étais… »', 'tous-les-jellypins'], ['Packs Livre & Peluche', 'tous-les-jellypins']
    ]
  },

  'personnalisation': {
    title: 'PERSONNALISATION', crumbs: ['Accueil'], landing: true,
    intro: 'Brodez un prénom, choisissez un pull : un Jellypin rien qu’à vous.',
    subs: [
      ['Lapins Personnalisés', 'lapins'], ['Pulls Personnalisés', 'lapins'],
      ['Premières Peluches Personnalisées', 'tous-les-jellypins'], ['Amuseables Personnalisés', 'amuseables']
    ]
  },

  'idees-cadeaux': {
    title: 'IDÉES CADEAUX', crumbs: ['Accueil'], landing: true,
    intro: 'Offrir un cadeau personnalisé, pour toutes les occasions.',
    subs: [
      ['Anniversaire', 'best-sellers'], ['Cadeaux Classiques', 'best-sellers'],
      ['Rentrée Scolaire', 'tous-les-jellypins'], ['Cadeaux pour les Gourmands', 'amuseables'],
      ['Découvrir les nouveautés estivales', 'nouveautes']
    ]
  },
  'noel': {
    title: "NOËL", crumbs: ['Accueil', 'Collections'], count: '79',
    intro: "Collection de Noël — rennes, pères Noël, sapins et gourmandises, à offrir ou à collectionner.",
    rows: [
    "pingouin-bonnet-rouge|Pingouin Bonnet Rouge|19,99€|Noël|img/noel/pingouin-bonnet-rouge.jpg",
    "bonhomme-pain-d-epices|Bonhomme Pain d'Épices|19,99€|Noël|img/noel/bonhomme-pain-d-epices.jpg",
    "sapin-de-noel|Sapin de Noël|19,99€|Noël|img/noel/sapin-de-noel.jpg",
    "bonhomme-de-neige-haut-de-forme|Bonhomme de Neige Haut-de-Forme|19,99€|Noël|img/noel/bonhomme-de-neige-haut-de-forme.jpg",
    "ours-polaire-echarpe-rouge|Ours Polaire Écharpe Rouge|19,99€|Noël|img/noel/ours-polaire-echarpe-rouge.jpg",
    "mug-chocolat-chaud|Mug Chocolat Chaud|19,99€|Noël|img/noel/mug-chocolat-chaud.jpg",
    "chaussette-de-noel|Chaussette de Noël|9,99€|Noël|img/noel/chaussette-de-noel.jpg",
    "renne-pull-flocon|Renne Pull Flocon|19,99€|Noël|img/noel/renne-pull-flocon.jpg",
    "maison-en-pain-d-epices|Maison en Pain d'Épices|19,99€|Noël|img/noel/maison-en-pain-d-epices.jpg",
    "pere-noel|Père Noël|19,99€|Noël|img/noel/pere-noel.jpg",
    "cadeau-rouge-noeud-dore|Cadeau Rouge Nœud Doré|9,99€|Noël|img/noel/cadeau-rouge-noeud-dore.jpg",
    "lutin-de-noel|Lutin de Noël|19,99€|Noël|img/noel/lutin-de-noel.jpg",
    "pudding-de-noel|Pudding de Noël|9,99€|Noël|img/noel/pudding-de-noel.jpg",
    "flocon-de-neige|Flocon de Neige|9,99€|Noël|img/noel/flocon-de-neige.jpg",
    "renard-pull-rouge|Renard Pull Rouge|19,99€|Noël|img/noel/renard-pull-rouge.jpg",
    "lapin-brun|Lapin Brun|19,99€|Noël|img/noel/lapin-brun.jpg",
    "ange-de-noel|Ange de Noël|19,99€|Noël|img/noel/ange-de-noel.jpg",
    "etoile-pain-d-epices|Étoile Pain d'Épices|9,99€|Noël|img/noel/etoile-pain-d-epices.jpg",
    "pingouin-pere-noel|Pingouin Père Noël|9,99€|Noël|img/noel/pingouin-pere-noel.jpg",
    "husky-bonnet-rouge|Husky Bonnet Rouge|9,99€|Noël|img/noel/husky-bonnet-rouge.jpg",
    "renne-bonnet-vert|Renne Bonnet Vert|9,99€|Noël|img/noel/renne-bonnet-vert.jpg",
    "couronne-de-noel|Couronne de Noël|19,99€|Noël|img/noel/couronne-de-noel.jpg",
    "sucre-d-orge|Sucre d'Orge|9,99€|Noël|img/noel/sucre-d-orge.jpg",
    "mug-latte-echarpe-verte|Mug Latte Écharpe Verte|9,99€|Noël|img/noel/mug-latte-echarpe-verte.jpg",
    "pingouin-bonnet-pompon|Pingouin Bonnet Pompon|9,99€|Noël|img/noel/pingouin-bonnet-pompon.jpg",
    "renne-endormi|Renne Endormi|9,99€|Noël|img/noel/renne-endormi.jpg",
    "gnome-de-noel|Gnome de Noël|9,99€|Noël|img/noel/gnome-de-noel.jpg",
    "ours-polaire-bonnet-bleu|Ours Polaire Bonnet Bleu|19,99€|Noël|img/noel/ours-polaire-bonnet-bleu.jpg",
    "pingouin-bonnet-rouge-tricot|Pingouin Bonnet Rouge Tricot|19,99€|Noël|img/noel/pingouin-bonnet-rouge-tricot.jpg",
    "bonhomme-de-neige-echarpe-carreaux|Bonhomme de Neige Écharpe Carreaux|19,99€|Noël|img/noel/bonhomme-de-neige-echarpe-carreaux.jpg",
    "renne-echarpe-verte|Renne Écharpe Verte|19,99€|Noël|img/noel/renne-echarpe-verte.jpg",
    "lapin-echarpe-bleue|Lapin Écharpe Bleue|19,99€|Noël|img/noel/lapin-echarpe-bleue.jpg",
    "ours-blanc-pull-rouge|Ours Blanc Pull Rouge|19,99€|Noël|img/noel/ours-blanc-pull-rouge.jpg",
    "pingouin-capuche-grise|Pingouin Capuche Grise|19,99€|Noël|img/noel/pingouin-capuche-grise.jpg",
    "ours-pull-flocons|Ours Pull Flocons|19,99€|Noël|img/noel/ours-pull-flocons.jpg",
    "sapin-etoile-doree|Sapin Étoile Dorée|19,99€|Noël|img/noel/sapin-etoile-doree.jpg",
    "chouette-bonnet-bleu|Chouette Bonnet Bleu|19,99€|Noël|img/noel/chouette-bonnet-bleu.jpg",
    "renard-echarpe-verte|Renard Écharpe Verte|19,99€|Noël|img/noel/renard-echarpe-verte.jpg",
    "bonhomme-pain-d-epices-noeud|Bonhomme Pain d'Épices Nœud|19,99€|Noël|img/noel/bonhomme-pain-d-epices-noeud.jpg",
    "phoque-echarpe-bleue|Phoque Écharpe Bleue|9,99€|Noël|img/noel/phoque-echarpe-bleue.jpg",
    "renne-echarpe-rouge|Renne Écharpe Rouge|19,99€|Noël|img/noel/renne-echarpe-rouge.jpg",
    "husky-echarpe-rouge|Husky Écharpe Rouge|19,99€|Noël|img/noel/husky-echarpe-rouge.jpg",
    "mug-rouge-flocons|Mug Rouge Flocons|19,99€|Noël|img/noel/mug-rouge-flocons.jpg",
    "pingouin-bonnet-pere-noel|Pingouin Bonnet Père Noël|19,99€|Noël|img/noel/pingouin-bonnet-pere-noel.jpg",
    "chalet-pain-d-epices|Chalet Pain d'Épices|19,99€|Noël|img/noel/chalet-pain-d-epices.jpg",
    "ours-creme-bonnet-bleu|Ours Crème Bonnet Bleu|19,99€|Noël|img/noel/ours-creme-bonnet-bleu.jpg",
    "duo-pingouins-echarpes|Duo Pingouins Écharpes|19,99€|Noël|img/noel/duo-pingouins-echarpes.jpg",
    "faon-echarpe-rouge|Faon Écharpe Rouge|19,99€|Noël|img/noel/faon-echarpe-rouge.jpg",
    "bonhomme-de-neige-bonnet-raye|Bonhomme de Neige Bonnet Rayé|19,99€|Noël|img/noel/bonhomme-de-neige-bonnet-raye.jpg",
    "elephant-echarpe-rouge|Éléphant Écharpe Rouge|19,99€|Noël|img/noel/elephant-echarpe-rouge.jpg",
    "boule-blanche-houx|Boule Blanche Houx|19,99€|Noël|img/noel/boule-blanche-houx.jpg",
    "lapin-brun-echarpe-rouge|Lapin Brun Écharpe Rouge|19,99€|Noël|img/noel/lapin-brun-echarpe-rouge.jpg",
    "voiture-rouge-sapin|Voiture Rouge Sapin|19,99€|Noël|img/noel/voiture-rouge-sapin.jpg",
    "chien-cache-oreilles|Chien Cache-Oreilles|19,99€|Noël|img/noel/chien-cache-oreilles.jpg",
    "ours-bonnet-vert|Ours Bonnet Vert|19,99€|Noël|img/noel/ours-bonnet-vert.jpg",
    "cheminee-de-noel|Cheminée de Noël|9,99€|Noël|img/noel/cheminee-de-noel.jpg",
    "pingouin-cache-oreilles|Pingouin Cache-Oreilles|9,99€|Noël|img/noel/pingouin-cache-oreilles.jpg",
    "chaussette-sucre-d-orge|Chaussette Sucre d'Orge|9,99€|Noël|img/noel/chaussette-sucre-d-orge.jpg",
    "ours-polaire-bonnet-pere-noel|Ours Polaire Bonnet Père Noël|9,99€|Noël|img/noel/ours-polaire-bonnet-pere-noel.jpg",
    "paresseux-flocon|Paresseux Flocon|9,99€|Noël|img/noel/paresseux-flocon.jpg",
    "renne-blanc-echarpe|Renne Blanc Écharpe|9,99€|Noël|img/noel/renne-blanc-echarpe.jpg",
    "montagne-enneigee|Montagne Enneigée|9,99€|Noël|img/noel/montagne-enneigee.jpg",
    "sapin-pain-d-epices|Sapin Pain d'Épices|9,99€|Noël|img/noel/sapin-pain-d-epices.jpg",
    "herisson-bonnet-bleu|Hérisson Bonnet Bleu|9,99€|Noël|img/noel/herisson-bonnet-bleu.jpg",
    "mug-chantilly-cannelle|Mug Chantilly Cannelle|9,99€|Noël|img/noel/mug-chantilly-cannelle.jpg",
    "renne-bonnet-rouge|Renne Bonnet Rouge|9,99€|Noël|img/noel/renne-bonnet-rouge.jpg",
    "ours-creme-bonnet-rouge|Ours Crème Bonnet Rouge|9,99€|Noël|img/noel/ours-creme-bonnet-rouge.jpg",
    "pingouin-capuche-rouge|Pingouin Capuche Rouge|9,99€|Noël|img/noel/pingouin-capuche-rouge.jpg",
    "moufle-rouge-flocon|Moufle Rouge Flocon|9,99€|Noël|img/noel/moufle-rouge-flocon.jpg",
    "renne-echarpe-verte-mini|Renne Écharpe Verte Mini|9,99€|Noël|img/noel/renne-echarpe-verte-mini.jpg",
    "lapin-creme-echarpe-rouge|Lapin Crème Écharpe Rouge|9,99€|Noël|img/noel/lapin-creme-echarpe-rouge.jpg",
    "traineau-de-cadeaux|Traîneau de Cadeaux|9,99€|Noël|img/noel/traineau-de-cadeaux.jpg",
    "ours-blanc-echarpe-bleue|Ours Blanc Écharpe Bleue|9,99€|Noël|img/noel/ours-blanc-echarpe-bleue.jpg",
    "ours-pull-bleu|Ours Pull Bleu|9,99€|Noël|img/noel/ours-pull-bleu.jpg",
    "ours-et-son-petit|Ours et Son Petit|9,99€|Noël|img/noel/ours-et-son-petit.jpg",
    "couronne-souriante|Couronne Souriante|9,99€|Noël|img/noel/couronne-souriante.jpg",
    "pingouin-bonnet-et-echarpe|Pingouin Bonnet et Écharpe|9,99€|Noël|img/noel/pingouin-bonnet-et-echarpe.jpg",
    "ours-bonnet-renne|Ours Bonnet Renne|9,99€|Noël|img/noel/ours-bonnet-renne.jpg",
    "ours-allonge-bonnet-bleu|Ours Allongé Bonnet Bleu|9,99€|Noël|img/noel/ours-allonge-bonnet-bleu.jpg"
    ]
  },
  'hiver': {
    title: "HIVER", crumbs: ['Accueil', 'Collections'], count: '18',
    intro: "Collection Hiver — ours polaires, pingouins et flocons pour toute la saison froide.",
    rows: [
    "ours-polaire-echarpe-bleue|Ours Polaire Écharpe Bleue|19,99€|Hiver|img/hiver/ours-polaire-echarpe-bleue.jpg",
    "bonhomme-de-neige-bonnet-bleu|Bonhomme de Neige Bonnet Bleu|19,99€|Hiver|img/hiver/bonhomme-de-neige-bonnet-bleu.jpg",
    "renne-echarpe-flocons|Renne Écharpe Flocons|19,99€|Hiver|img/hiver/renne-echarpe-flocons.jpg",
    "loup-echarpe-bleue|Loup Écharpe Bleue|19,99€|Hiver|img/hiver/loup-echarpe-bleue.jpg",
    "mug-chocolat-cannelle|Mug Chocolat Cannelle|19,99€|Hiver|img/hiver/mug-chocolat-cannelle.jpg",
    "pingouins-en-luge|Pingouins en Luge|19,99€|Hiver|img/hiver/pingouins-en-luge.jpg",
    "bonhomme-pain-d-epices-echarpe|Bonhomme Pain d'Épices Écharpe|9,99€|Hiver|img/hiver/bonhomme-pain-d-epices-echarpe.jpg",
    "lapin-bonnet-bleu|Lapin Bonnet Bleu|19,99€|Hiver|img/hiver/lapin-bonnet-bleu.jpg",
    "morse-bonnet-rouge|Morse Bonnet Rouge|19,99€|Hiver|img/hiver/morse-bonnet-rouge.jpg",
    "flocon-de-neige-souriant|Flocon de Neige Souriant|19,99€|Hiver|img/hiver/flocon-de-neige-souriant.jpg",
    "renne-grelot|Renne Grelot|19,99€|Hiver|img/hiver/renne-grelot.jpg",
    "renard-blanc-echarpe|Renard Blanc Écharpe|19,99€|Hiver|img/hiver/renard-blanc-echarpe.jpg",
    "chalet-de-montagne|Chalet de Montagne|9,99€|Hiver|img/hiver/chalet-de-montagne.jpg",
    "bebe-phoque-echarpe|Bébé Phoque Écharpe|9,99€|Hiver|img/hiver/bebe-phoque-echarpe.jpg",
    "moufles-flocons|Moufles Flocons|9,99€|Hiver|img/hiver/moufles-flocons.jpg",
    "ours-polaire-allonge|Ours Polaire Allongé|9,99€|Hiver|img/hiver/ours-polaire-allonge.jpg",
    "pingouin-boule-de-neige|Pingouin Boule de Neige|9,99€|Hiver|img/hiver/pingouin-boule-de-neige.jpg",
    "renne-endormi-echarpe|Renne Endormi Écharpe|9,99€|Hiver|img/hiver/renne-endormi-echarpe.jpg"
    ]
  },
  'automne': {
    title: "AUTOMNE", crumbs: ['Accueil', 'Collections'], count: '40',
    intro: "Collection Automne — renards, citrouilles, champignons et feuilles d'érable.",
    rows: [
    "renard-echarpe-carreaux|Renard Écharpe Carreaux|19,99€|Automne|img/automne/renard-echarpe-carreaux.jpg",
    "ours-feuille-d-erable|Ours Feuille d'Érable|19,99€|Automne|img/automne/ours-feuille-d-erable.jpg",
    "lapin-bonnet-citrouille|Lapin Bonnet Citrouille|19,99€|Automne|img/automne/lapin-bonnet-citrouille.jpg",
    "herisson-feuille-rouge|Hérisson Feuille Rouge|19,99€|Automne|img/automne/herisson-feuille-rouge.jpg",
    "ecureuil-gland|Écureuil Gland|19,99€|Automne|img/automne/ecureuil-gland.jpg",
    "oie-echarpe-rouge|Oie Écharpe Rouge|19,99€|Automne|img/automne/oie-echarpe-rouge.jpg",
    "hibou-echarpe-carreaux|Hibou Écharpe Carreaux|9,99€|Automne|img/automne/hibou-echarpe-carreaux.jpg",
    "ours-feuille-de-chene|Ours Feuille de Chêne|19,99€|Automne|img/automne/ours-feuille-de-chene.jpg",
    "citrouille-souriante|Citrouille Souriante|19,99€|Automne|img/automne/citrouille-souriante.jpg",
    "ecureuil-echarpe-automne|Écureuil Écharpe Automne|19,99€|Automne|img/automne/ecureuil-echarpe-automne.jpg",
    "champignon-rouge|Champignon Rouge|19,99€|Automne|img/automne/champignon-rouge.jpg",
    "chat-noir-citrouille|Chat Noir Citrouille|19,99€|Automne|img/automne/chat-noir-citrouille.jpg",
    "ours-couronne-de-feuilles|Ours Couronne de Feuilles|19,99€|Automne|img/automne/ours-couronne-de-feuilles.jpg",
    "raton-laveur-feuille|Raton Laveur Feuille|19,99€|Automne|img/automne/raton-laveur-feuille.jpg",
    "herisson-bonnet-rouge|Hérisson Bonnet Rouge|19,99€|Automne|img/automne/herisson-bonnet-rouge.jpg",
    "lapin-panier-d-automne|Lapin Panier d'Automne|19,99€|Automne|img/automne/lapin-panier-d-automne.jpg",
    "souche-d-arbre|Souche d'Arbre|19,99€|Automne|img/automne/souche-d-arbre.jpg",
    "panier-de-feuilles|Panier de Feuilles|9,99€|Automne|img/automne/panier-de-feuilles.jpg",
    "fantome-citrouille|Fantôme Citrouille|19,99€|Automne|img/automne/fantome-citrouille.jpg",
    "lapin-allonge-echarpe|Lapin Allongé Écharpe|19,99€|Automne|img/automne/lapin-allonge-echarpe.jpg",
    "renard-echarpe-verte-2|Renard Écharpe Verte|9,99€|Automne|img/automne/renard-echarpe-verte-2.jpg",
    "feuille-jaune|Feuille Jaune|9,99€|Automne|img/automne/feuille-jaune.jpg",
    "grosse-citrouille|Grosse Citrouille|9,99€|Automne|img/automne/grosse-citrouille.jpg",
    "elan-echarpe-carreaux|Élan Écharpe Carreaux|19,99€|Automne|img/automne/elan-echarpe-carreaux.jpg",
    "oie-bonnet-rouge|Oie Bonnet Rouge|9,99€|Automne|img/automne/oie-bonnet-rouge.jpg",
    "herisson-pomme|Hérisson Pomme|9,99€|Automne|img/automne/herisson-pomme.jpg",
    "mug-chantilly-feuille|Mug Chantilly Feuille|9,99€|Automne|img/automne/mug-chantilly-feuille.jpg",
    "ecureuil-roux-gland|Écureuil Roux Gland|9,99€|Automne|img/automne/ecureuil-roux-gland.jpg",
    "ours-chapeau-citrouille|Ours Chapeau Citrouille|9,99€|Automne|img/automne/ours-chapeau-citrouille.jpg",
    "champignon-blanc-a-pois|Champignon Blanc à Pois|9,99€|Automne|img/automne/champignon-blanc-a-pois.jpg",
    "chat-noir-feuilles|Chat Noir Feuilles|19,99€|Automne|img/automne/chat-noir-feuilles.jpg",
    "chien-echarpe-automne|Chien Écharpe Automne|9,99€|Automne|img/automne/chien-echarpe-automne.jpg",
    "renard-endormi|Renard Endormi|9,99€|Automne|img/automne/renard-endormi.jpg",
    "pile-de-livres-d-automne|Pile de Livres d'Automne|9,99€|Automne|img/automne/pile-de-livres-d-automne.jpg",
    "citrouille-latte|Citrouille Latte|9,99€|Automne|img/automne/citrouille-latte.jpg",
    "epouvantail|Épouvantail|9,99€|Automne|img/automne/epouvantail.jpg",
    "lapin-tournesols|Lapin Tournesols|9,99€|Automne|img/automne/lapin-tournesols.jpg",
    "ecureuil-rouge|Écureuil Rouge|9,99€|Automne|img/automne/ecureuil-rouge.jpg",
    "herisson-bonnet-tricot|Hérisson Bonnet Tricot|9,99€|Automne|img/automne/herisson-bonnet-tricot.jpg",
    "citrouille-feuille|Citrouille Feuille|9,99€|Automne|img/automne/citrouille-feuille.jpg"
    ]
  },
  'printemps': {
    title: "PRINTEMPS", crumbs: ['Accueil', 'Collections'], count: '40',
    intro: "Collection Printemps — lapins fleuris, poussins et jardin en éveil.",
    rows: [
    "lapin-bouquet-de-marguerites|Lapin Bouquet de Marguerites|19,99€|Printemps|img/printemps/lapin-bouquet-de-marguerites.jpg",
    "poussin-couronne-de-fleurs|Poussin Couronne de Fleurs|9,99€|Printemps|img/printemps/poussin-couronne-de-fleurs.jpg",
    "agneau-couronne-de-fleurs|Agneau Couronne de Fleurs|19,99€|Printemps|img/printemps/agneau-couronne-de-fleurs.jpg",
    "tulipe-rose|Tulipe Rose|9,99€|Printemps|img/printemps/tulipe-rose.jpg",
    "grenouille-marguerite|Grenouille Marguerite|9,99€|Printemps|img/printemps/grenouille-marguerite.jpg",
    "oie-rubans-fleuris|Oie Rubans Fleuris|19,99€|Printemps|img/printemps/oie-rubans-fleuris.jpg",
    "ecureuil-bouquet|Écureuil Bouquet|19,99€|Printemps|img/printemps/ecureuil-bouquet.jpg",
    "abeille|Abeille|19,99€|Printemps|img/printemps/abeille.jpg",
    "coccinelle|Coccinelle|19,99€|Printemps|img/printemps/coccinelle.jpg",
    "oiseau-bleu-couronne|Oiseau Bleu Couronne|19,99€|Printemps|img/printemps/oiseau-bleu-couronne.jpg",
    "lapin-carotte|Lapin Carotte|19,99€|Printemps|img/printemps/lapin-carotte.jpg",
    "papillon-pastel|Papillon Pastel|19,99€|Printemps|img/printemps/papillon-pastel.jpg",
    "marguerite-souriante|Marguerite Souriante|9,99€|Printemps|img/printemps/marguerite-souriante.jpg",
    "faon-couronne-de-fleurs|Faon Couronne de Fleurs|19,99€|Printemps|img/printemps/faon-couronne-de-fleurs.jpg",
    "escargot-couronne|Escargot Couronne|19,99€|Printemps|img/printemps/escargot-couronne.jpg",
    "lapin-creme-noeud-rose|Lapin Crème Nœud Rose|19,99€|Printemps|img/printemps/lapin-creme-noeud-rose.jpg",
    "arrosoir-fleuri-vert|Arrosoir Fleuri Vert|19,99€|Printemps|img/printemps/arrosoir-fleuri-vert.jpg",
    "herisson-couronne-de-fleurs|Hérisson Couronne de Fleurs|9,99€|Printemps|img/printemps/herisson-couronne-de-fleurs.jpg",
    "lapin-rose-couronne|Lapin Rose Couronne|19,99€|Printemps|img/printemps/lapin-rose-couronne.jpg",
    "pot-de-fleurs-marguerites|Pot de Fleurs Marguerites|9,99€|Printemps|img/printemps/pot-de-fleurs-marguerites.jpg",
    "caneton-noeud-bleu|Caneton Nœud Bleu|9,99€|Printemps|img/printemps/caneton-noeud-bleu.jpg",
    "agneau-noeud-lavande|Agneau Nœud Lavande|19,99€|Printemps|img/printemps/agneau-noeud-lavande.jpg",
    "abeille-ailes-deployees|Abeille Ailes Déployées|9,99€|Printemps|img/printemps/abeille-ailes-deployees.jpg",
    "fleur-rose|Fleur Rose|19,99€|Printemps|img/printemps/fleur-rose.jpg",
    "duo-de-cerises|Duo de Cerises|19,99€|Printemps|img/printemps/duo-de-cerises.jpg",
    "lapin-creme-bouquet|Lapin Crème Bouquet|9,99€|Printemps|img/printemps/lapin-creme-bouquet.jpg",
    "grenouille-verte|Grenouille Verte|9,99€|Printemps|img/printemps/grenouille-verte.jpg",
    "arrosoir-violet|Arrosoir Violet|9,99€|Printemps|img/printemps/arrosoir-violet.jpg",
    "oie-couronne-fleurie|Oie Couronne Fleurie|9,99€|Printemps|img/printemps/oie-couronne-fleurie.jpg",
    "panier-de-fleurs|Panier de Fleurs|19,99€|Printemps|img/printemps/panier-de-fleurs.jpg",
    "lapin-bandana-fleuri|Lapin Bandana Fleuri|19,99€|Printemps|img/printemps/lapin-bandana-fleuri.jpg",
    "carotte|Carotte|9,99€|Printemps|img/printemps/carotte.jpg",
    "marguerite-blanche|Marguerite Blanche|9,99€|Printemps|img/printemps/marguerite-blanche.jpg",
    "lapin-bleu-noeud|Lapin Bleu Nœud|9,99€|Printemps|img/printemps/lapin-bleu-noeud.jpg",
    "poussin-couronne-fleurie|Poussin Couronne Fleurie|9,99€|Printemps|img/printemps/poussin-couronne-fleurie.jpg",
    "faon-allonge-fleurs|Faon Allongé Fleurs|19,99€|Printemps|img/printemps/faon-allonge-fleurs.jpg",
    "bouquet-de-tulipes|Bouquet de Tulipes|9,99€|Printemps|img/printemps/bouquet-de-tulipes.jpg",
    "chenille|Chenille|9,99€|Printemps|img/printemps/chenille.jpg",
    "coccinelle-noire|Coccinelle Noire|9,99€|Printemps|img/printemps/coccinelle-noire.jpg",
    "papillon-rose|Papillon Rose|9,99€|Printemps|img/printemps/papillon-rose.jpg"
    ]
  }
};
